import uuid from "react-uuid";

export const footer1 = [
    {
        idGrid: undefined,
        type: "img",
        left: "31%",
        top: 209,
        id: uuid(),
        width: 543,
        height: 423,
        inGrid: true,
        isMulti: false,
        InfoIcon: "",
        styleDefault: {
            backgroundColor: "",
            color: "",
            fontSize: "",
            fontFamily: "",
            borderRadius: "0px",
            borderStyle: "",
            borderColor: "",
            fontWeight: "normal",
            textAlign: "",
            borderWidth: "0px",
            textTransform: "",
            lineHeight: "",
        },
        src: "https://i.ibb.co/CPgMRLQ/social-media-ga2fd0a7dd-1920-removebg-preview.png",
        href: "",
        valueItem: "",
        linkImage:
            "https://i.ibb.co/CPgMRLQ/social-media-ga2fd0a7dd-1920-removebg-preview.png",
    },
    {
        idGrid: undefined,
        type: "button",
        left: "9%",
        top: 360,
        id: uuid(),
        width: 200,
        height: 50,
        inGrid: true,
        isMulti: false,
        InfoIcon: "",
        styleDefault: {
            border: "none",
            backgroundColor: "transparent",
            color: "rgb(221, 90, 19)",
            borderWidth: "1px",
            borderStyle: "outset",
            borderColor: "rgb(255, 0, 0)",
            padding: "12px",
            textAlign: "center",
            textTransform: "uppercase",
            borderRadius: "4px",
            fontSize: "20px",
            fontFamily: "",
            fontWeight: "bold",
            lineHeight: "",
        },
        src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQq9zZ0dsOIYyjwZdkWKTE_kuxtRplsy9dexPnXEzCsMRNXXATXEmrELQz9i7z1aeStYJI&usqp=CAU",
        href: "",
        valueItem: "contact me",
    },
    {
        idGrid: undefined,
        type: "icon",
        left: "18%",
        top: 451,
        id: uuid(),
        width: 60,
        height: 60,
        inGrid: true,
        isMulti: false,
        InfoIcon: "Github",
        styleDefault: {
            border: "none",
            borderWidth: "1px",
            borderStyle: "solid",
            borderColor: "rgba(0, 0, 0, 0)",
            color: "rgb(0, 0, 0)",
            backgroundColor: "rgba(0, 0, 0, 0)",
            fontSize: "",
            fontFamily: "",
            borderRadius: "0px",
            fontWeight: "normal",
            textAlign: "",
            textTransform: "",
            lineHeight: "",
        },
        src: "",
        href: "http://localhost:3000/template1",
        valueItem: "",
    },
    {
        idGrid: undefined,
        type: "icon",
        left: "4%",
        top: 451,
        id: uuid(),
        width: 60,
        height: 60,
        inGrid: true,
        isMulti: false,
        InfoIcon: "Instagram",
        styleDefault: {
            border: "none",
            borderWidth: "1px",
            borderStyle: "solid",
            borderColor: "rgba(0, 0, 0, 0)",
            color: "red",
            backgroundColor: "",
            fontSize: "",
            fontFamily: "",
            borderRadius: "0px",
            fontWeight: "normal",
            textAlign: "",
            textTransform: "",
            lineHeight: "",
        },
        src: "",
        href: "http://localhost:3000/template1",
        valueItem: "",
    },
    {
        idGrid: undefined,
        type: "icon",
        left: "27%",
        top: 451,
        id: uuid(),
        width: 60,
        height: 60,
        inGrid: true,
        isMulti: false,
        InfoIcon: "Facebook",
        styleDefault: {
            border: "none",
            borderWidth: "1px",
            borderStyle: "solid",
            borderColor: "rgba(0, 0, 0, 0)",
            color: "blue",
            backgroundColor: "rgba(0, 0, 0, 0)",
            fontSize: "",
            fontFamily: "",
            borderRadius: "0px",
            fontWeight: "normal",
            textAlign: "",
            textTransform: "",
            lineHeight: "",
        },
        src: "",
        href: "http://localhost:3000/template1",
        valueItem: "",
    },
    {
        idGrid: undefined,
        type: "icon",
        left: "11%",
        top: 451,
        id: uuid(),
        width: 60,
        height: 60,
        inGrid: true,
        isMulti: false,
        InfoIcon: "Linkedin",
        styleDefault: {
            border: "none",
            borderWidth: "1px",
            borderStyle: "solid",
            borderColor: "rgba(0, 0, 0, 0)",
            color: "rgb(0, 255, 255)",
            backgroundColor: "rgba(0, 0, 0, 0)",
            fontSize: "",
            fontFamily: "",
            borderRadius: "0px",
            fontWeight: "normal",
            textAlign: "",
            textTransform: "",
            lineHeight: "",
        },
        src: "",
        href: "http://localhost:3000/template1",
        valueItem: "",
    },
    {
        idGrid: undefined,
        type: "input",
        left: "74%",
        top: 389,
        id: uuid(),
        width: 265,
        height: 154,
        inGrid: true,
        isMulti: false,
        InfoIcon: "",
        styleDefault: {
            border: "none",
            backgroundColor: "transparent",
            color: "rgb(204, 204, 204)",
            borderWidth: "1px",
            borderStyle: "outset",
            borderColor: "rgb(255, 255, 255)",
            padding: "12px",
            fontSize: "",
            fontFamily: "",
            borderRadius: "0px",
            fontWeight: "normal",
            textAlign: "",
            textTransform: "",
            lineHeight: "",
        },
        src: "",
        href: "",
        valueItem: "<Address>",
        textValue: "<Address>",
    },
    {
        idGrid: undefined,
        type: "button",
        left: "76%",
        top: 315,
        id: uuid(),
        width: 200,
        height: 50,
        inGrid: true,
        isMulti: false,
        InfoIcon: "",
        styleDefault: {
            border: "none",
            backgroundColor: "transparent",
            color: "rgb(221, 90, 19)",
            borderWidth: "1px",
            borderStyle: "outset",
            borderColor: "rgb(255, 0, 0)",
            padding: "12px",
            textAlign: "center",
            textTransform: "uppercase",
            borderRadius: "4px",
            fontSize: "24px",
            fontFamily: "",
            fontWeight: "bold",
            lineHeight: "",
        },
        src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQq9zZ0dsOIYyjwZdkWKTE_kuxtRplsy9dexPnXEzCsMRNXXATXEmrELQz9i7z1aeStYJI&usqp=CAU",
        href: "",
        valueItem: "Address",
    },
];
