import uuid from "react-uuid";

export const DefaultItemInGridTemplate1 = [
  {
    id: uuid(),
    type: "background",
    left: 0,
    top: 0,
    width: 1442,
    height: 500,
    inGrid: true,
    isMulti: false,
    InfoIcon: "",
    styleDefault: {
      border: "none",
      backgroundColor: "rgb(204, 204, 204)",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "none",
      borderColor: "initial",
      fontWeight: "",
      textAlign: "",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
      borderSize: "initial",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "input",
    left: 503,
    top: 125,
    width: 382,
    height: 86,
    inGrid: true,
    isMulti: false,
    InfoIcon: "",
    styleDefault: {
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(31, 163, 136)",
      borderWidth: "1px",
      borderStyle: "outset",
      borderColor: "var(--primary)",
      padding: "12px",
      fontSize: "25px",
      fontFamily: '"Sf mono"',
      borderRadius: "",
      fontWeight: "bold",
      textAlign: "center",
      textTransform: "uppercase",
      lineHeight: "",
      borderSize: "1px",
    },
    valueItem: "Enter header",
    textValue: "Enter header",
  },
];
