import uuid from "react-uuid";

export const DefaultItemInGridTemplate3 = [
  {
    id: uuid(),
    type: "img",
    left: 738,
    top: 130,
    width: 600,
    height: 250,
    inGrid: true,
    isMulti: false,
    center: true,
    src: "https://i.ibb.co/F5445KH/icon-removebg-preview.png",
    styleDefault: {
      backgroundColor: "transparent",
      borderColor: "transparent",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "",
      fontWeight: "",
      textAlign: "",
      borderWidth: "",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "input",
    left: 925,
    top: 342,
    width: 500,
    height: 80,
    inGrid: true,
    isMulti: false,
    valueItem: "<About>",
    center: true,
    styleDefault: {
      backgroundColor: "transparent",
      fontSize: "18px",
      textAlign: "center",
      border: "1px solid #ccc",
      color: "rgb(0, 0, 0)",
      fontFamily: "Poppins",
      lineHeight: "26px",
      boxShadow: "14px 17px 115px 0px rgba(0,0,0,0.75)",
      zIndex: -100,
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      fontWeight: "",
      borderWidth: "1px",
      textTransform: "",
    },
    textValue: "<About>",
  },
  {
    id: uuid(),
    type: "button",
    left: 725,
    top: 41,
    width: 200,
    height: 48,
    inGrid: true,
    isMulti: false,
    valueItem: "<Name page>",
    center: true,
    styleDefault: {
      backgroundColor: "transparent",
      fontSize: "18px",
      textAlign: "center",
      border: "none",
      color: "rgb(0, 0, 0)",
      fontFamily: "Poppins",
      lineHeight: "26px",
      borderBottom: "1px double #ccc ",
      borderRight: "1px double #ccc ",
      padding: 12,
      minHeight: 48,
      borderRadius: "",
      borderStyle: "none double double none",
      borderColor: "",
      fontWeight: "",
      borderWidth: "",
      textTransform: "",
    },
  },
  {
    id: uuid(),
    type: "input",
    left: 326,
    top: 129,
    width: 400,
    height: 50,
    inGrid: true,
    isMulti: false,
    valueItem: "[Enter title]",
    styleDefault: {
      backgroundColor: "transparent",
      fontSize: "24px",
      fontWeight: "bold",
      textAlign: "center",
      border: "3px outset  rgb(255, 69, 0)",
      color: "rgb(255, 0, 255)",
      fontFamily: "Poppins",
      lineHeight: "26px",
      boxShadow: "14px 17px 115px 0px rgb(255, 69, 0)",
      borderRadius: "100px",
      textTransform: "uppercase",
      borderStyle: "outset",
      borderColor: "rgb(255, 69, 0)",
      borderWidth: "3px",
    },
    textValue: "[Enter title]",
  },
  {
    id: uuid(),
    type: "input",
    left: 929,
    top: 274,
    width: 500,
    height: 48,
    inGrid: true,
    isMulti: false,
    valueItem: "<Enter text>",
    center: true,
    styleDefault: {
      backgroundColor: "rgba(0, 0, 0, 0)",
      fontSize: "18px",
      textAlign: "center",
      border: "1px outset  rgb(255, 69, 0)",
      color: "rgb(32, 8, 8)",
      fontFamily: "Poppins",
      lineHeight: "26px",
      borderRadius: "20px",
      boxShadow: "14px 17px 115px 0px rgb(255, 69, 0)",
      borderStyle: "outset",
      borderColor: "rgb(255, 69, 0)",
      fontWeight: "",
      borderWidth: "1px",
      textTransform: "",
      borderSize: "1px",
    },
    textValue: "<Enter text>",
  },
  {
    id: uuid(),
    type: "img",
    left: 498,
    top: 547,
    width: 300,
    height: 350,
    inGrid: true,
    isMulti: false,
    center: true,
    src: "https://i.ibb.co/CnXLkqg/Pngtree-cartoon-hand-drawn-online-education-4986516.png",
    styleDefault: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
      borderRight: "1px double #ccc",
      borderTop: "1px double #ccc",
      boxShadow: " 10px 10px 106px -33px rgba(240,43,53,1)",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "double double none none",
      borderColor: "",
      fontWeight: "",
      textAlign: "",
      borderWidth: "",
      textTransform: "",
      lineHeight: "",
      borderSize: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "button",
    left: 864,
    top: 600,
    width: 200,
    height: 48,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "About",
    styleDefault: {
      fontWeight: "bold",
      fontSize: "24px",
      color: "rgb(106, 90, 205)",
      border: "3px outset #DC143C",
      wordSpacing: "4px",
      backgroundColor: "transparent",
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      fontFamily: "",
      borderStyle: "outset",
      borderColor: "rgb(220, 20, 60)",
      textAlign: "center",
      borderWidth: "3px",
      lineHeight: "36px",
      borderSize: "3px",
    },
    src: "",
  },
  {
    id: uuid(),
    type: "input",
    left: 714,
    top: 682,
    width: 500,
    height: 100,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Your About>",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(0, 0, 0)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      fontSize: "",
      fontFamily: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "<Your About>",
  },
  {
    id: uuid(),
    type: "input",
    left: 734,
    top: 1023,
    width: 400,
    height: 48,
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "[Your project]",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(106, 90, 205)",
      backgroundColor: "transparent",
      border: "3px outset #DC143C",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      textTransform: "uppercase",
      fontFamily: "",
      borderStyle: "outset",
      borderColor: "rgb(220, 20, 60)",
      borderWidth: "3px",
      lineHeight: "",
    },
    textValue: "[Your project]",
  },
  {
    id: uuid(),
    type: "input",
    left: 728,
    top: 1135,
    width: 600,
    height: 48,
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "<Describe>",
    styleDefault: {
      color: "rgb(0, 0, 0)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      margin: "0 auto",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      fontFamily: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      fontWeight: "",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "<Describe>",
  },
  {
    id: uuid(),
    type: "img",
    left: 568,
    top: 1414,
    width: 300,
    height: 350,
    inGrid: true,
    isMulti: false,
    center: true,
    src: "https://i.ibb.co/KzzV8qS/Pngtree-network-education-online-education-illustration-6187862.png",
    styleDefault: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
      borderRight: "1px double #ccc",
      borderTop: "1px double #ccc",
      boxShadow: " 10px 10px 106px -33px rgba(240,43,53,1)",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "double double none none",
      borderColor: "",
      fontWeight: "",
      textAlign: "",
      borderWidth: "",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "input",
    left: 866,
    top: 1491,
    width: 200,
    height: 50,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "Education",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(201, 171, 122)",
      backgroundColor: "transparent",
      border: "3px outset #DC143C",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      fontFamily: "",
      borderStyle: "outset",
      borderColor: "rgb(220, 20, 60)",
      borderWidth: "3px",
      lineHeight: "40px",
      borderSize: "3px",
    },
    textValue: "Education",
  },
  {
    id: uuid(),
    type: "input",
    left: 808,
    top: 1664,
    width: 260,
    height: 64,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Details major>",
    styleDefault: {
      color: "rgb(0, 0, 0)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      margin: "0 auto",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      fontFamily: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      fontWeight: "",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "55px",
      borderSize: "1px",
    },
    textValue: "<Details major>",
  },
  {
    id: uuid(),
    type: "input",
    left: 800,
    top: 1413,
    width: 200,
    height: 50,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "About work",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(201, 171, 122)",
      backgroundColor: "transparent",
      border: "3px outset #DC143C",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      fontFamily: "",
      borderStyle: "outset",
      borderColor: "rgb(220, 20, 60)",
      borderWidth: "3px",
      lineHeight: "40px",
      borderSize: "3px",
    },
    textValue: "About work",
  },
  {
    id: uuid(),
    type: "input",
    left: 779,
    top: 1556,
    width: 252,
    height: 69,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Details work>",
    styleDefault: {
      color: "rgb(0, 0, 0)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      margin: "0 auto",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      fontFamily: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      fontWeight: "",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "62px",
      borderSize: "1px",
    },
    textValue: "<Details work>",
  },
  {
    id: uuid(),
    type: "input",
    left: 798,
    top: 2085,
    width: 200,
    height: 50,
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "<Your feeling>",
    styleDefault: {
      color: "rgb(204, 204, 204)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "24px",
      fontFamily: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      fontWeight: "",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "<Your feeling>",
  },
  {
    id: uuid(),
    type: "input",
    left: 667,
    top: 1903,
    width: 200,
    height: 50,
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "Other projects",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(179, 7, 60)",
      backgroundColor: "transparent",
      border: "3px outset #DC143C",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      fontFamily: "",
      borderStyle: "outset",
      borderColor: "rgb(220, 20, 60)",
      borderWidth: "3px",
      lineHeight: "42px",
      borderSize: "3px",
    },
    textValue: "Other projects",
  },
  {
    id: uuid(),
    type: "img",
    left: 205,
    top: 1993,
    width: 200,
    height: 150,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "3px outset  rgb(255, 69, 0)",
      borderRight: "1px double #ccc",
      borderTop: "1px double #ccc",
      boxShadow: "14px 17px 115px 0px rgb(255, 69, 0)",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "double double outset outset",
      borderColor:
        "rgb(204, 204, 204) rgb(204, 204, 204) rgb(255, 69, 0) rgb(255, 69, 0)",
      fontWeight: "",
      textAlign: "",
      borderWidth: "1px 1px 3px 3px",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "img",
    left: 437,
    top: 2000,
    width: 200,
    height: 150,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      boxShadow: " 10px 10px 106px -33px rgba(240,43,53,1)",
      border: "none",
      borderRadius: "24px",
      backgroundColor: "transparent",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "none",
      borderColor: "initial",
      fontWeight: "",
      textAlign: "",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "img",
    left: 314,
    top: 2166,
    width: 200,
    height: 150,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "",
      borderColor: "",
      fontWeight: "",
      textAlign: "",
      borderWidth: "",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "input",
    left: 944,
    top: 2022,
    width: 250,
    height: 50,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Technology used>",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(0, 0, 0)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "24px",
      fontFamily: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      lineHeight: "45px",
      borderSize: "1px",
    },
    textValue: "<Technology used>",
  },
  {
    id: uuid(),
    type: "input",
    left: 872,
    top: 2176,
    width: 346,
    height: 99,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Describes>",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(0, 0, 0)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "12px",
      fontFamily: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      lineHeight: "44px",
      borderSize: "1px",
    },
    textValue: "<Describes>",
  },
  {
    id: uuid(),
    type: "input",
    left: 705,
    top: 2516,
    width: 250,
    height: 50,
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "Contact me",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(179, 7, 60)",
      backgroundColor: "transparent",
      border: "3px outset #DC143C",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      fontFamily: "",
      borderStyle: "outset",
      borderColor: "rgb(220, 20, 60)",
      borderWidth: "3px",
      lineHeight: "46px",
      borderSize: "3px",
    },
    textValue: "Contact me",
  },
  {
    id: uuid(),
    type: "img",
    left: 714,
    top: 2594,
    width: 300,
    height: 250,
    inGrid: true,
    isMulti: false,
    center: true,
    src: "https://i.ibb.co/dg8wwp3/Pngtree-contact-us-flat-design-style-5874427.png",
    styleDefault: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "none",
      borderColor: "initial",
      fontWeight: "",
      textAlign: "",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "input",
    left: 960,
    top: 2589,
    width: 250,
    height: 230,
    inGrid: true,
    isMulti: false,
    valueItem: "[Your detail, address]",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(0, 0, 0)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "14px",
      borderRadius: "24px",
      fontFamily: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "[Your detail, address]",
  },
  {
    id: uuid(),
    type: "button",
    left: 264,
    top: 2643,
    width: 167,
    height: 119,
    inGrid: true,
    isMulti: false,
    valueItem: "<Your social networks>",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(0, 0, 0)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "14px",
      borderRadius: "360px",
      fontFamily: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "47px",
      borderSize: "1px",
      id: uuid(),
    },
    src: "",
  },
  {
    type: "icon",
    height: 42,
    width: 76,
    left: 300,
    top: 2758,
    inGrid: true,
    isMulti: false,
    InfoIcon: "Facebook",
    styleDefault: {
      color: "rgb(27, 64, 152)",
      backgroundColor: "",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "",
      border: "3px outset #DC143C",
      fontSize: "",
      fontFamily: "",
      borderStyle: "",
      borderColor: "",
      fontWeight: "",
      textAlign: "",
      borderWidth: "",
      textTransform: "",
      lineHeight: "",
      borderSize: "",
    },
    id: uuid(),
    valueItem: "",
    href: "http://localhost:3000/template3",
  },
  {
    type: "icon",
    height: 44,
    width: 76,
    left: 379,
    top: 2618,
    inGrid: true,
    isMulti: false,
    InfoIcon: "Instagram",
    styleDefault: {
      color: "rgb(215, 55, 111)",
      textTransform: "",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "",
      border: "3px outset #DC143C",
      backgroundColor: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "",
      borderColor: "",
      fontWeight: "",
      textAlign: "",
      borderWidth: "",
      lineHeight: "",
      borderSize: "",
    },
    id: uuid(),
    valueItem: "",
    href: "http://localhost:3000/template3",
  },
  {
    type: "icon",
    height: 50,
    width: 87,
    left: 225,
    top: 2615,
    inGrid: true,
    isMulti: false,
    InfoIcon: "Github",
    styleDefault: {
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "",
      border: "3px outset #DC143C",
      backgroundColor: "",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "",
      borderColor: "",
      fontWeight: "",
      textAlign: "",
      borderWidth: "",
      textTransform: "",
      lineHeight: "",
      borderSize: "3px",
    },
    id: uuid(),
    valueItem: "",
    href: "http://localhost:3000/template3",
  },
];
