import uuid from "react-uuid";

export const DefaultItemInGridTemplate2 = [
  {
    id: "9b4011da-66bd-e02b-e731-9414b9d67d98",
    type: "background",
    left: "0%",
    top: 0,
    width: 1442,
    height: 650,
    inGrid: true,
    isMulti: false,
    InfoIcon: "",
    styleDefault: {
      border: "none",
      backgroundColor: "rgb(0, 0, 51)",
      objectFit: "cover",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "none",
      borderColor: "initial",
      fontWeight: "",
      textAlign: "",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
      borderSize: "initial",
    },
    valueItem: "",
  },
  {
    id: "f2a7b923-1e58-134a-8248-de798e79e201",
    type: "input",
    left: "3.6061026352288486%",
    top: 30,
    width: 102,
    height: 38,
    inGrid: true,
    isMulti: false,
    InfoIcon: "",
    styleDefault: {
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(255, 255, 255)",
      borderWidth: "1px",
      borderStyle: "outset",
      borderColor: "rgba(0, 0, 0, 0)",
      padding: "12px",
      fontSize: "31px",
      fontFamily: "Poppins",
      borderRadius: "",
      fontWeight: "",
      textAlign: "",
      textTransform: "",
      lineHeight: "",
      borderSize: "1px",
    },
    valueItem: "Portf",
    textValue: "Portf",
  },
  {
    id: "d3b73986-0722-2a65-8843-60f8c6f70aa5",
    type: "input",
    left: "8.668515950069349%",
    top: 30,
    width: "100",
    height: 40,
    inGrid: true,
    isMulti: false,
    InfoIcon: "",
    styleDefault: {
      backgroundColor: "transparent",
      color: "rgb(166, 46, 38)",
      borderWidth: "1px",
      borderStyle: "outset",
      borderColor: "rgba(0, 0, 0, 0)",
      padding: "12px",
      fontSize: "30px",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "",
      textAlign: "",
      textTransform: "",
      lineHeight: "",
      borderSize: "1px",
    },
    valueItem: "olio",
    textValue: "olio",
  },
  {
    id: "9b3551c3-f7eb-03c7-a978-f5399b1fa8cd",
    type: "a",
    left: "29%",
    top: 30,
    width: 100,
    height: 30,
    inGrid: true,
    isMulti: false,
    InfoIcon: "",
    styleDefault: {
      borderWidth: "1px",
      borderStyle: "solid",
      borderColor: "rgba(0, 0, 0, 0)",
      padding: "12px",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(234, 31, 16)",
      fontSize: "14px",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "",
      textAlign: "",
      textTransform: "",
      lineHeight: "",
      borderSize: "1px",
    },
    href: "http://localhost:3000/template1#home",
    valueItem: "Home",
    textValue: "Home",
  },
  {
    id: "e07e6365-e0af-72e4-3ca3-c84f05225708",
    type: "a",
    left: "38%",
    top: 30,
    width: 100,
    height: 30,
    inGrid: true,
    isMulti: false,
    InfoIcon: "",
    styleDefault: {
      borderWidth: "1px",
      borderStyle: "solid",
      borderColor: "rgba(0, 0, 0, 0)",
      padding: "12px",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(255, 255, 255)",
      fontSize: "14px",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "",
      textAlign: "",
      textTransform: "",
      lineHeight: "",
      borderSize: "1px",
    },
    href: "http://localhost:3000/template1#about",
    valueItem: "About us",
    textValue: "About us",
  },
  {
    id: "38dcf41a-d11b-76c7-1456-af14c19922f8",
    type: "a",
    left: "47%",
    top: 30,
    width: 100,
    height: 30,
    inGrid: true,
    isMulti: false,
    InfoIcon: "",
    styleDefault: {
      borderWidth: "1px",
      borderStyle: "solid",
      borderColor: "rgba(0, 0, 0, 0)",
      padding: "12px",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(255, 255, 255)",
      fontSize: "14px",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "",
      textAlign: "",
      textTransform: "",
      lineHeight: "",
      borderSize: "1px",
    },
    href: "http://localhost:3000/template1#services",
    valueItem: "Services",
    textValue: "Services",
  },
  {
    id: "1eef0659-4f02-ee57-dc2d-359025aab642",
    type: "a",
    left: "55%",
    top: 30,
    width: 100,
    height: 30,
    inGrid: true,
    isMulti: false,
    InfoIcon: "",
    styleDefault: {
      borderWidth: "1px",
      borderStyle: "solid",
      borderColor: "rgba(0, 0, 0, 0)",
      padding: "12px",
      backgroundColor: "",
      color: "rgb(255, 255, 255)",
      fontSize: "14px",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "",
      textAlign: "",
      textTransform: "",
      lineHeight: "",
      borderSize: "1px",
    },
    href: "http://localhost:3000/template1#skills",
    valueItem: "Skills",
    textValue: "Skills",
  },
  {
    id: "a18b9c31-eecb-9090-31c3-2c43593c4ad1",
    type: "a",
    left: "63%",
    top: 30,
    width: 120,
    height: 30,
    inGrid: true,
    isMulti: false,
    InfoIcon: "",
    styleDefault: {
      borderWidth: "1px",
      borderStyle: "solid",
      borderColor: "rgba(0, 0, 0, 0)",
      padding: "12px",
      backgroundColor: "",
      color: "rgb(255, 255, 255)",
      fontSize: "14px",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "",
      textAlign: "",
      textTransform: "",
      lineHeight: "",
      borderSize: "1px",
    },
    href: "http://localhost:3000/template1#contact",
    valueItem: "Contact me",
    textValue: "Contact me",
  },
  {
    id: "0ec73837-b26e-9faf-1ca3-496bbd67bdea",
    type: "button",
    left: "87.1012482662968%",
    top: 34,
    width: 100,
    height: 35,
    inGrid: true,
    isMulti: false,
    InfoIcon: "",
    styleDefault: {
      backgroundColor: "rgb(255, 29, 81)",
      color: "rgb(208, 201, 179)",
      borderWidth: "1px",
      borderStyle: "outset",
      borderColor: "rgba(0, 0, 0, 0)",
      padding: "12px",
      textAlign: "center",
      textTransform: "uppercase",
      fontSize: "",
      fontFamily: "",
      borderRadius: "12px",
      fontWeight: "",
      lineHeight: "18px",
      borderSize: "1px",
    },
    src: "",
    valueItem: "Contact",
  },
  {
    id: "8d5567da-1697-3f22-2514-cc44dcff187a",
    type: "input",
    left: "29.819694868238557%",
    top: 174,
    width: 200,
    height: 60,
    inGrid: true,
    isMulti: false,
    InfoIcon: "",
    styleDefault: {
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(234, 31, 16)",
      borderWidth: "1px",
      borderStyle: "outset",
      borderColor: "rgba(0, 0, 0, 0)",
      padding: "12px",
      fontSize: "24px",
      fontFamily: "Poppins",
      borderRadius: "",
      fontWeight: "bold",
      textAlign: "center",
      textTransform: "uppercase",
      lineHeight: "",
      borderSize: "1px",
    },
    valueItem: "<name>",
    textValue: "<name>",
  },
  {
    id: "222fb1d1-be0c-494d-b9a5-f7c3a9fb2bba",
    type: "input",
    left: "18.030513176144243%",
    top: 176,
    width: 253,
    height: 53,
    inGrid: true,
    isMulti: false,
    InfoIcon: "",
    styleDefault: {
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(255, 255, 255)",
      borderWidth: "1px",
      borderStyle: "outset",
      borderColor: "rgba(0, 0, 0, 0)",
      padding: "12px",
      fontSize: "17px",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "",
      textAlign: "",
      textTransform: "",
      lineHeight: "",
      borderSize: "1px",
    },
    valueItem: "My full name is",
    textValue: "My full name is",
  },
  {
    id: "f9fc84a1-287d-3219-0f59-4099cef5f622",
    type: "input",
    left: "23.57836338418863%",
    top: 234,
    width: 256,
    height: 64,
    inGrid: true,
    isMulti: false,
    InfoIcon: "",
    styleDefault: {
      backgroundColor: "transparent",
      color: "rgb(103, 88, 218)",
      borderWidth: "1px",
      borderStyle: "outset",
      borderColor: "rgba(0, 0, 0, 0)",
      padding: "12px",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "",
      textAlign: "center",
      textTransform: "uppercase",
      lineHeight: "",
      borderSize: "1px",
    },
    valueItem: "I'm a website developer",
    textValue: "I'm a website developer",
  },
  {
    id: "162b75e7-58f3-0254-40bf-5cdcacd3474a",
    type: "input",
    left: "16.08876560332871%",
    top: 319,
    width: 300,
    height: 52,
    inGrid: true,
    isMulti: false,
    InfoIcon: "",
    styleDefault: {
      backgroundColor: "rgb(255, 255, 255)",
      color: "rgb(32, 31, 35)",
      borderWidth: "1px",
      borderStyle: "outset",
      borderColor: "var(--primary)",
      padding: "12px",
      fontSize: "15px",
      fontFamily: "Alegreya",
      borderRadius: "24px",
      fontWeight: "",
      textAlign: "",
      textTransform: "",
      lineHeight: "",
      borderSize: "1px",
    },
    valueItem: "Enter your email  ",
  },
  {
    id: "2f4631ab-60e4-c217-2530-aebc992715a9",
    type: "button",
    left: "39.042995839112336%",
    top: 327,
    width: 151,
    height: 36,
    inGrid: true,
    isMulti: false,
    InfoIcon: "",
    styleDefault: {
      backgroundColor: "rgb(255, 29, 81)",
      color: "rgb(255, 255, 255)",
      borderWidth: "1px",
      borderStyle: "outset",
      borderColor: "rgb(255, 0, 0)",
      padding: "12px",
      textAlign: "center",
      textTransform: "uppercase",
      fontSize: "",
      fontFamily: "",
      borderRadius: "23px",
      fontWeight: "",
      lineHeight: "10px",
      borderSize: "1px",
    },
    src: "",
    valueItem: "send",
  },
  {
    id: "6890fed3-80b4-f16a-4f67-08e22e3cd6ec",
    type: "div",
    left: "51.10957004160886%",
    top: 350,
    width: 178,
    height: 161,
    inGrid: true,
    isMulti: false,
    InfoIcon: "",
    styleDefault: {
      border: " 1px solid #ccc",
      backgroundColor: "rgb(0, 0, 0)",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "124px",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      fontWeight: "",
      textAlign: "",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
      borderSize: "1px",
    },
    valueItem: "",
  },
  {
    id: "5c73a5e2-274a-39a3-1c46-0be5fa887954",
    type: "img",
    left: "55.47850208044382%",
    top: 154,
    width: "250",
    height: 284,
    inGrid: true,
    isMulti: false,
    InfoIcon: "",
    styleDefault: {
      objectFit: "cover",
      backgroundColor: "",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "",
      borderColor: "",
      fontWeight: "",
      textAlign: "",
      borderWidth: "",
      textTransform: "",
      lineHeight: "",
      borderSize: "",
    },
    src: "https://i.ibb.co/rHr1Btk/Pngtree-a-male-student-is-studying-7649439.png",
    valueItem: "",
  },
  {
    id: "80b7efab-bd01-49a6-b6e7-2b1ee4f94a93",
    type: "background",
    left: "0%",
    top: 646,
    width: 1442,
    height: 650,
    inGrid: true,
    isMulti: false,
    InfoIcon: "",
    styleDefault: {
      border: "none",
      backgroundColor: "rgb(0, 0, 51)",
      objectFit: "cover",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "none",
      borderColor: "initial",
      fontWeight: "",
      textAlign: "",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
      borderSize: "initial",
    },
    valueItem: "",
  },
  {
    id: "82231107-fe06-1ead-e8e9-9597dfd59d5f",
    type: "img",
    left: "21.63661581137309%",
    top: 798,
    width: 448,
    height: 354,
    inGrid: true,
    isMulti: false,
    InfoIcon: "",
    styleDefault: {
      objectFit: "cover",
      backgroundColor: "",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "",
      borderColor: "",
      fontWeight: "",
      textAlign: "",
      borderWidth: "",
      textTransform: "",
      lineHeight: "",
      borderSize: "",
    },
    src: "https://i.ibb.co/9TNNxxP/Pngtree-a-man-wearing-vr-glasses-7649408.png",
    valueItem: "",
  },
  {
    id: "4775ad2e-2e63-1923-9b9d-7b4d007e5dfd",
    type: "input",
    left: "62.13592233009708%",
    top: 804,
    width: "200",
    height: 40,
    inGrid: true,
    isMulti: false,
    InfoIcon: "",
    styleDefault: {
      backgroundColor: "transparent",
      color: "rgb(177, 129, 129)",
      borderWidth: "1px",
      borderStyle: "outset",
      borderColor: "rgb(255, 29, 81)",
      padding: "12px",
      fontSize: "18px",
      fontFamily: "Acme",
      borderRadius: "",
      fontWeight: "bold",
      textAlign: "center",
      textTransform: "uppercase",
      lineHeight: "18px",
      borderSize: "1px",
    },
    valueItem: "About me ",
    textValue: "About me ",
  },
  {
    id: "bdd7eca8-c679-7f9f-c289-df29da4d09e6",
    type: "input",
    left: "59.986130374479885%",
    top: 894,
    width: "250",
    height: 250,
    inGrid: true,
    isMulti: false,
    InfoIcon: "",
    styleDefault: {
      backgroundColor: "transparent",
      color: "rgb(255, 255, 255)",
      borderWidth: "1px",
      borderStyle: "outset",
      borderColor: "rgba(0, 0, 0, 0)",
      padding: "12px",
      fontSize: "18px",
      fontFamily: "Bitter",
      borderRadius: "",
      fontWeight: "",
      textAlign: "center",
      textTransform: "",
      lineHeight: "27px",
      borderSize: "1px",
    },
    valueItem: "enter text",
    textValue: "enter text",
  },
  {
    id: "66e1e608-cb07-e68d-40e4-8418f8a8a863",
    type: "background",
    left: "0%",
    top: 1292,
    width: 1442,
    height: 650,
    inGrid: true,
    isMulti: false,
    InfoIcon: "",
    styleDefault: {
      border: "none",
      backgroundColor: "rgb(0, 0, 51)",
      objectFit: "cover",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "none",
      borderColor: "initial",
      fontWeight: "",
      textAlign: "",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
      borderSize: "initial",
    },
    valueItem: "",
  },
  {
    id: "26efaae5-924f-46fd-19c3-f6efb0e11081",
    type: "input",
    left: "44%",
    top: 1381,
    width: 200,
    height: 40,
    inGrid: true,
    isMulti: false,
    InfoIcon: "",
    styleDefault: {
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(177, 129, 129)",
      borderWidth: "1px",
      borderStyle: "outset",
      borderColor: "var(--primary)",
      padding: "12px",
      fontSize: "18px",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "bold",
      textAlign: "center",
      textTransform: "uppercase",
      lineHeight: "18px",
      borderSize: "1px",
    },
    valueItem: "Our Services",
    textValue: "Our Services",
  },
  {
    id: "58227855-a0df-f357-19a0-20db0170f31d",
    type: "div",
    left: "20.87378640776699%",
    top: 1530,
    width: 200,
    height: 100,
    inGrid: true,
    isMulti: false,
    InfoIcon: "",
    styleDefault: {
      border: " 1px solid #ccc",
      backgroundColor: "rgb(175, 67, 67)",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      fontWeight: "",
      textAlign: "",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
      borderSize: "1px",
    },
    valueItem: "",
  },
  {
    id: "1e5fc885-eb5d-64f4-f8a5-9f36036e55ab",
    type: "div",
    left: "44.105409153952834%",
    top: 1530,
    width: 200,
    height: 100,
    inGrid: true,
    isMulti: false,
    InfoIcon: "",
    styleDefault: {
      border: " 1px solid #ccc",
      backgroundColor: "rgb(175, 67, 67)",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      fontWeight: "",
      textAlign: "",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
      borderSize: "1px",
    },
    valueItem: "",
  },
  {
    id: "9eee8c7f-9ae4-d6f7-5157-56e985d6fe15",
    type: "div",
    left: "66.01941747572815%",
    top: 1530,
    width: 200,
    height: 100,
    inGrid: true,
    isMulti: false,
    InfoIcon: "",
    styleDefault: {
      border: " 1px solid #ccc",
      backgroundColor: "rgb(175, 67, 67)",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      fontWeight: "",
      textAlign: "",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
      borderSize: "1px",
    },
    valueItem: "",
  },
];
