import uuid from "react-uuid";

export const DefaultItemInGridTemplate2 = [
  {
    id: uuid(),
    type: "img",
    left: 0,
    top: 0,
    width: "100%",
    height: 502,
    inGrid: true,
    isMulti: false,
    src: "https://images.unsplash.com/photo-1497864149936-d3163f0c0f4b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80",
    styleDefault: {
      backgroundColor: "",
      padding: 0,
      borderWidth: "0px",
      borderStyle: "none",
      borderColor: "transparent",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "",
      textAlign: "",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "div",
    left: 0,
    top: 500,
    width: "100%",
    height: 510,
    inGrid: true,
    isMulti: false,
    valueItem: "",
    styleDefault: {
      backgroundColor: "rgb(24, 45, 71)",
      borderWidth: "0px",
      borderStyle: "none",
      borderColor: "transparent",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "",
      textAlign: "",
      textTransform: "",
      lineHeight: "",
    },
  },
  {
    id: uuid(),
    type: "div",
    left: -2,
    top: 953,
    width: 1442,
    height: 541,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      backgroundColor: "rgb(9, 29, 53)",
      border: "none",
      borderWidth: "0px",
      borderStyle: "none",
      borderColor: "transparent",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "",
      textAlign: "",
      textTransform: "",
      lineHeight: "",
      borderSize: "0px",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "div",
    left: -12,
    top: 1484,
    width: 1471,
    height: 534,
    inGrid: true,
    isMulti: false,
    valueItem: "",
    styleDefault: {
      backgroundColor: "rgb(24, 45, 71)",
      borderWidth: "0px",
      borderStyle: "none",
      borderColor: "transparent",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "",
      textAlign: "",
      textTransform: "",
      lineHeight: "",
      borderSize: "0px",
    },
  },
  {
    id: uuid(),
    type: "div",
    left: 0,
    top: 2000,
    width: 1442,
    height: 510,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      backgroundColor: "rgb(9, 29, 53)",
      borderWidth: "0px",
      borderStyle: "none",
      borderColor: "transparent",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "",
      textAlign: "",
      textTransform: "",
      lineHeight: "",
      borderSize: "0px",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "div",
    left: 0,
    top: 2495,
    width: 1442,
    height: 510,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      backgroundColor: "rgb(24, 45, 71)",
      borderWidth: "0px",
      borderStyle: "none",
      borderColor: "transparent",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "",
      textAlign: "",
      textTransform: "",
      lineHeight: "",
      borderSize: "0px",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "img",
    left: 971,
    top: 88,
    width: 300,
    height: 350,
    inGrid: true,
    isMulti: false,
    src: "https://i.imgur.com/uo3V1fn.png",
    styleDefault: {
      borderRadius: "50px",
      backgroundColor: "transparent",
      borderColor: "transparent",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "",
      fontWeight: "",
      textAlign: "",
      borderWidth: "",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "input",
    left: 253,
    top: 127,
    width: 400,
    height: 50,
    inGrid: true,
    isMulti: false,
    valueItem: "[Enter title]",
    styleDefault: {
      backgroundColor: "transparent",
      fontSize: "24px",
      fontWeight: "bold",
      textAlign: "center",
      border: "1px solid #ccc",
      color: "rgb(220, 20, 60)",
      fontFamily: "Poppins",
      lineHeight: "26px",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
    },
    textValue: "[Enter title]",
  },
  {
    id: uuid(),
    type: "input",
    left: 195,
    top: 243,
    width: 500,
    height: 48,
    inGrid: true,
    isMulti: false,
    valueItem: "<Enter text>",
    styleDefault: {
      backgroundColor: "transparent",
      fontSize: "18px",
      textAlign: "center",
      border: "1px solid #ccc",
      color: "rgb(255, 255, 224)",
      fontFamily: "Poppins",
      lineHeight: "26px",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      fontWeight: "",
      borderWidth: "1px",
      textTransform: "",
    },
    textValue: "<Enter text>",
  },
  {
    id: uuid(),
    type: "button",
    left: 146,
    top: 26,
    width: 200,
    height: 48,
    inGrid: true,
    isMulti: false,
    valueItem: "Enter text !!!",
    styleDefault: {
      backgroundColor: "transparent",
      fontSize: "18px",
      textAlign: "center",
      border: "none",
      color: "rgb(255, 0, 0)",
      fontFamily: "Poppins",
      lineHeight: "26px",
      borderBottom: "1px double #ccc ",
      borderRight: "1px double #ccc ",
      padding: 12,
      minHeight: 48,
      borderRadius: "",
      borderStyle: "none double double none",
      borderColor: "",
      fontWeight: "",
      borderWidth: "",
      textTransform: "",
    },
  },
  {
    id: uuid(),
    type: "img",
    left: 263,
    top: 572,
    width: 382,
    height: 367,
    inGrid: true,
    isMulti: false,
    src: "https://i.imgur.com/MCXD87T.png",
    styleDefault: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
      borderRight: "1px double #ccc",
      borderTop: "1px double #ccc",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "double double none none",
      borderColor: "",
      fontWeight: "",
      textAlign: "",
      borderWidth: "",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "button",
    left: 831,
    top: 613,
    width: 200,
    height: 48,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "About",
    styleDefault: {
      fontWeight: "bold",
      fontSize: "24px",
      color: "rgb(106, 90, 205)",
      border: "1px solid #ccc",
      wordSpacing: "4px",
      backgroundColor: "transparent",
      textTransform: "uppercase",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      textAlign: "center",
      borderWidth: "1px",
      lineHeight: "",
      borderSize: "1px",
    },
    src: "",
  },
  {
    id: uuid(),
    type: "input",
    left: 728,
    top: 740,
    width: 378,
    height: 52,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Your About>",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(255, 255, 255)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
      borderSize: "1px",
    },
    textValue: "<Your About>",
  },
  {
    id: uuid(),
    type: "input",
    left: 705,
    top: 1105,
    width: 400,
    height: 50,
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "[Your Offered Services]",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(106, 90, 205)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
      borderSize: "1px",
    },
  },
  {
    id: uuid(),
    type: "input",
    left: 698,
    top: 1226,
    width: 600,
    height: 48,
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "<Describe>",
    styleDefault: {
      color: "rgb(255, 255, 255)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      margin: "0 auto",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      fontWeight: "",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "<Describe>",
  },
  {
    id: uuid(),
    type: "img",
    left: 763,
    top: 1584,
    width: 400,
    height: 400,
    inGrid: true,
    isMulti: false,
    heading: true,
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(201, 171, 122)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      height: 400,
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "input",
    left: 344,
    top: 1664,
    width: 300,
    height: 48,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "[Feedback from client]",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(201, 171, 122)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "[Feedback from client]",
  },
  {
    id: uuid(),
    type: "input",
    left: 299,
    top: 1777,
    width: 400,
    height: 48,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Your slogan>",
    styleDefault: {
      color: "rgb(255, 255, 255)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      margin: "0 auto",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      fontWeight: "",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "<Your slogan>",
  },
  {
    id: uuid(),
    type: "input",
    left: 722,
    top: 2073,
    width: 400,
    height: 50,
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "[Your project]",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(179, 7, 60)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
      borderSize: "1px",
    },
    textValue: "[Your project]",
  },
  {
    id: uuid(),
    type: "input",
    left: 724,
    top: 2218,
    width: 600,
    height: 48,
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "<Technology used>",
    styleDefault: {
      color: "rgb(255, 255, 255)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      margin: "0 auto",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      fontWeight: "",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "<Technology used>",
  },
  {
    id: uuid(),
    type: "input",
    left: 685,
    top: 2553,
    width: 250,
    height: 100,
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "Looking ForWard to working with everyone!",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(255, 248, 220)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      lineHeight: "32px",
      textTransform: "uppercase",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      borderSize: "1px",
    },
    textValue: "Looking ForWard to working with everyone!",
  },
  {
    id: uuid(),
    type: "img",
    left: 687,
    top: 2686,
    width: 360,
    height: 214,
    inGrid: true,
    isMulti: false,
    center: true,
    src: "https://i.imgur.com/PAvCNbh.png",
    styleDefault: {
      borderRadius: "50px",
      backgroundColor: "transparent",
      borderColor: "transparent",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "",
      fontWeight: "",
      textAlign: "",
      borderWidth: "",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "input",
    left: 229,
    top: 2741,
    width: 205,
    height: 100,
    inGrid: true,
    isMulti: false,
    valueItem: "[Your detail, address]",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(255, 255, 255)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      height: 100,
      fontSize: "14px",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "[Your detail, address]",
  },
  {
    id: uuid(),
    type: "button",
    left: 263,
    top: 2622,
    width: 153,
    height: 56,
    inGrid: true,
    isMulti: false,
    valueItem: "About",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(255, 255, 255)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "14px",
      textTransform: "uppercase",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      lineHeight: "",
      borderSize: "1px",
    },
    src: "",
  },
  {
    id: uuid(),
    type: "input",
    left: 917,
    top: 2622,
    width: 268,
    height: 100,
    inGrid: true,
    isMulti: false,
    valueItem: "[Address detail,your number]",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(255, 255, 255)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "14px",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "[Address detail,your number]",
  },
  {
    id: uuid(),
    type: "a",
    left: 1142,
    top: 2803,
    width: 100,
    height: 50,
    inGrid: true,
    isMulti: false,
    href: "http://localhost:3000/template2#",
    textValue: "facebook",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(255, 255, 255)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      minHeight: 50,
      fontSize: "14px",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      textAlign: "center",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
      borderSize: "1px",
    },
    valueItem: "facebook",
  },
  {
    id: uuid(),
    type: "a",
    left: 1007,
    top: 2802,
    width: 107,
    height: 50,
    inGrid: true,
    isMulti: false,
    href: "http://localhost:3000/template2#",
    textValue: "Instagram",
    valueItem: "Instagram",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(255, 255, 255)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      minHeight: 50,
      fontSize: "14px",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      textAlign: "center",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
  },
  {
    id: uuid(),
    type: "a",
    left: 877,
    top: 2804,
    width: 100,
    height: 50,
    inGrid: true,
    isMulti: false,
    href: "http://localhost:3000/template2#",
    textValue: "Youtube",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(255, 255, 255)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      minHeight: 50,
      fontSize: "14px",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      textAlign: "center",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
      borderSize: "1px",
    },
    valueItem: "Youtube",
  },
];
