import uuid from "react-uuid";

export const DefaultItemInGridTemplate1 = [
  {
    id: uuid(),
    type: "background",
    left: "0%",
    top: 0,
    width: 1442,
    height: 600,
    inGrid: true,
    isMulti: false,
    InfoIcon: "",
    styleDefault: {
      border: "none",
      backgroundColor: "rgb(54, 89, 135)",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "none",
      borderColor: "initial",
      fontWeight: "",
      textAlign: "",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
      borderSize: "initial",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "input",
    left: "31.62274618585299%",
    top: 136,
    width: 548,
    height: 80,
    inGrid: true,
    isMulti: false,
    InfoIcon: "",
    styleDefault: {
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(204, 204, 204)",
      borderWidth: "1px",
      borderStyle: "outset",
      borderColor: "var(--primary)",
      padding: "12px",
      fontSize: "18px",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "",
      textAlign: "center",
      textTransform: "",
      lineHeight: "",
      borderSize: "1px",
    },
    valueItem: "Enter text",
  },
];
