import uuid from "react-uuid";

export const DefaultItemInGridTemplate3 = [
  {
    id: uuid(),
    type: "img",
    left: "50%",
    top: 100,
    width: 600,
    height: 250,
    inGrid: true,
    isMulti: false,
    center: true,
    src: "https://i.ibb.co/F5445KH/icon-removebg-preview.png",
    styleDefault: {
      backgroundColor: "transparent",
      borderColor: "transparent",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "",
      fontWeight: "",
      textAlign: "",
      borderWidth: "",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "input",
    left: "70%",
    top: 380,
    width: 500,
    height: 80,
    inGrid: true,
    isMulti: false,
    valueItem: "<About>",
    center: true,
    styleDefault: {
      backgroundColor: "transparent",
      fontSize: "18px",
      textAlign: "center",
      border: "1px solid #ccc",
      color: "rgb(0, 0, 0)",
      fontFamily: "Poppins",
      lineHeight: "26px",
      boxShadow: "14px 17px 115px 0px rgba(0,0,0,0.75)",
      zIndex: -100,
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      fontWeight: "",
      borderWidth: "1px",
      textTransform: "",
    },
    textValue: "<About>",
  },
  {
    id: uuid(),
    type: "button",
    left: "50%",
    top: 12,
    width: 200,
    height: 48,
    inGrid: true,
    isMulti: false,
    valueItem: "<Name page>",
    center: true,
    styleDefault: {
      backgroundColor: "transparent",
      fontSize: "18px",
      textAlign: "center",
      border: "none",
      color: "rgb(0, 0, 0)",
      fontFamily: "Poppins",
      lineHeight: "26px",
      borderBottom: "1px double #ccc ",
      borderRight: "1px double #ccc ",
      padding: 12,
      minHeight: 48,
      borderRadius: "",
      borderStyle: "none double double none",
      borderColor: "",
      fontWeight: "",
      borderWidth: "",
      textTransform: "",
    },
  },
  {
    id: uuid(),
    type: "input",
    left: 59,
    top: 120,
    width: 400,
    height: 50,
    inGrid: true,
    isMulti: false,
    valueItem: "[Enter title]",
    styleDefault: {
      backgroundColor: "transparent",
      fontSize: "24px",
      fontWeight: "bold",
      textAlign: "center",
      border: "3px outset  rgb(255, 69, 0)",
      color: "rgb(255, 0, 255)",
      fontFamily: "Poppins",
      lineHeight: "26px",
      boxShadow: "14px 17px 115px 0px rgb(255, 69, 0)",
      borderRadius: "100px",
      textTransform: "uppercase",
      borderStyle: "outset",
      borderColor: "rgb(255, 69, 0)",
      borderWidth: "3px",
    },
    textValue: "[Enter title]",
  },
  {
    id: uuid(),
    type: "input",
    left: 655,
    top: 267,
    width: 500,
    height: 48,
    inGrid: true,
    isMulti: false,
    valueItem: "<Enter text>",
    center: true,
    styleDefault: {
      backgroundColor: "rgba(0, 0, 0, 0)",
      fontSize: "18px",
      textAlign: "center",
      border: "1px outset  rgb(255, 69, 0)",
      color: "rgb(32, 8, 8)",
      fontFamily: "Poppins",
      lineHeight: "26px",
      borderRadius: "20px",
      boxShadow: "14px 17px 115px 0px rgb(255, 69, 0)",
      borderStyle: "outset",
      borderColor: "rgb(255, 69, 0)",
      fontWeight: "",
      borderWidth: "1px",
      textTransform: "",
      borderSize: "1px",
    },
    textValue: "<Enter text>",
  },
  {
    id: uuid(),
    type: "img",
    left: 200,
    top: 560,
    width: 300,
    height: 350,
    inGrid: true,
    isMulti: false,
    center: true,
    src: "https://i.ibb.co/CnXLkqg/Pngtree-cartoon-hand-drawn-online-education-4986516.png",
    styleDefault: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
      borderRight: "1px double #ccc",
      borderTop: "1px double #ccc",
      boxShadow: " 10px 10px 106px -33px rgba(240,43,53,1)",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "double double none none",
      borderColor: "",
      fontWeight: "",
      textAlign: "",
      borderWidth: "",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "button",
    left: "55%",
    top: 650,
    width: 200,
    height: 48,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "About",
    styleDefault: {
      fontWeight: "bold",
      fontSize: "24px",
      color: "rgb(106, 90, 205)",
      border: "3px outset #DC143C",
      wordSpacing: "4px",
      backgroundColor: "transparent",
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      fontFamily: "",
      borderStyle: "outset",
      borderColor: "rgb(220, 20, 60)",
      textAlign: "center",
      borderWidth: "3px",
      lineHeight: "36px",
      borderSize: "3px",
    },
    src: "",
  },
  {
    id: uuid(),
    type: "input",
    left: "calc(40% + 21px)",
    top: 734,
    width: 500,
    height: 100,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Your About>",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(0, 0, 0)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      fontSize: "",
      fontFamily: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "<Your About>",
  },
  {
    id: uuid(),
    type: "input",
    left: "50%",
    top: 1040,
    width: 400,
    height: 48,
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "[Your project]",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(106, 90, 205)",
      backgroundColor: "transparent",
      border: "3px outset #DC143C",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      textTransform: "uppercase",
      fontFamily: "",
      borderStyle: "outset",
      borderColor: "rgb(220, 20, 60)",
      borderWidth: "3px",
      lineHeight: "",
    },
    textValue: "[Your project]",
  },
  {
    id: uuid(),
    type: "input",
    left: "50%",
    top: 1120,
    width: 600,
    height: 48,
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "<Describe>",
    styleDefault: {
      color: "rgb(0, 0, 0)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      margin: "0 auto",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      fontFamily: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      fontWeight: "",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "<Describe>",
  },
  {
    id: uuid(),
    type: "img",
    left: "50%",
    top: 1520,
    width: 300,
    height: 350,
    inGrid: true,
    isMulti: false,
    center: true,
    src: "https://i.ibb.co/KzzV8qS/Pngtree-network-education-online-education-illustration-6187862.png",
    styleDefault: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
      borderRight: "1px double #ccc",
      borderTop: "1px double #ccc",
      boxShadow: " 10px 10px 106px -33px rgba(240,43,53,1)",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "double double none none",
      borderColor: "",
      fontWeight: "",
      textAlign: "",
      borderWidth: "",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "input",
    left: 70,
    top: 1540,
    width: 200,
    height: 50,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "Education",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(201, 171, 122)",
      backgroundColor: "transparent",
      border: "3px outset #DC143C",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      fontFamily: "",
      borderStyle: "outset",
      borderColor: "rgb(220, 20, 60)",
      borderWidth: "3px",
      lineHeight: "40px",
      borderSize: "3px",
    },
    textValue: "Education",
  },
  {
    id: uuid(),
    type: "input",
    left: 50,
    top: 1609,
    width: 260,
    height: 64,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Details major>",
    styleDefault: {
      color: "rgb(0, 0, 0)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      margin: "0 auto",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      fontFamily: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      fontWeight: "",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "55px",
      borderSize: "1px",
    },
  },
  {
    id: uuid(),
    type: "input",
    left: "70%",
    top: 1540,
    width: 200,
    height: 50,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "About work",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(201, 171, 122)",
      backgroundColor: "transparent",
      border: "3px outset #DC143C",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      fontFamily: "",
      borderStyle: "outset",
      borderColor: "rgb(220, 20, 60)",
      borderWidth: "3px",
      lineHeight: "40px",
      borderSize: "3px",
    },
    textValue: "About work",
  },
  {
    id: uuid(),
    type: "input",
    left: 645,
    top: 1608,
    width: 252,
    height: 69,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Details work>",
    styleDefault: {
      color: "rgb(0, 0, 0)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      margin: "0 auto",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      fontFamily: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      fontWeight: "",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "62px",
      borderSize: "1px",
    },
  },
  {
    id: uuid(),
    type: "input",
    left: "50%",
    top: 1900,
    width: 200,
    height: 48,
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "<Your feeling>",
    styleDefault: {
      color: "rgb(204, 204, 204)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "24px",
      fontFamily: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      fontWeight: "",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "<Your feeling>",
  },
  {
    id: uuid(),
    type: "input",
    left: 744,
    top: 2141,
    width: 200,
    height: 50,
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "Other projects",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(179, 7, 60)",
      backgroundColor: "transparent",
      border: "3px outset #DC143C",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      fontFamily: "",
      borderStyle: "outset",
      borderColor: "rgb(220, 20, 60)",
      borderWidth: "3px",
      lineHeight: "42px",
      borderSize: "3px",
    },
  },
  {
    id: uuid(),
    type: "img",
    left: 50,
    top: 2120,
    width: 200,
    height: 150,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "3px outset  rgb(255, 69, 0)",
      borderRight: "1px double #ccc",
      borderTop: "1px double #ccc",
      boxShadow: "14px 17px 115px 0px rgb(255, 69, 0)",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "double double outset outset",
      borderColor:
        "rgb(204, 204, 204) rgb(204, 204, 204) rgb(255, 69, 0) rgb(255, 69, 0)",
      fontWeight: "",
      textAlign: "",
      borderWidth: "1px 1px 3px 3px",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "img",
    left: 274,
    top: 2080,
    width: 200,
    height: 150,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      boxShadow: " 10px 10px 106px -33px rgba(240,43,53,1)",
      border: "none",
      borderRadius: "24px",
      backgroundColor: "transparent",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "none",
      borderColor: "initial",
      fontWeight: "",
      textAlign: "",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "img",
    left: 274,
    top: 2250,
    width: 200,
    height: 150,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "",
      borderColor: "",
      fontWeight: "",
      textAlign: "",
      borderWidth: "",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "input",
    left: 518,
    top: 2082,
    width: 250,
    height: 50,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Technology used>",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(0, 0, 0)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "24px",
      fontFamily: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      lineHeight: "45px",
      borderSize: "1px",
    },
    textValue: "<Technology used>",
  },
  {
    id: uuid(),
    type: "input",
    left: 516,
    top: 2198,
    width: 192,
    height: 50,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Field of work>",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(0, 0, 0)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "24px",
      fontFamily: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      lineHeight: "43px",
      borderSize: "1px",
    },
    textValue: "<Field of work>",
  },
  {
    id: uuid(),
    type: "input",
    left: 505,
    top: 2289,
    width: 346,
    height: 99,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Describes>",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(0, 0, 0)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "12px",
      fontFamily: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      lineHeight: "44px",
      borderSize: "1px",
    },
    textValue: "<Describes>",
  },
  {
    id: uuid(),
    type: "input",
    left: "50%",
    top: 2540,
    width: 250,
    height: 50,
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "Contact me",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(179, 7, 60)",
      backgroundColor: "transparent",
      border: "3px outset #DC143C",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      fontFamily: "",
      borderStyle: "outset",
      borderColor: "rgb(220, 20, 60)",
      borderWidth: "3px",
      lineHeight: "46px",
      borderSize: "3px",
    },
    textValue: "Contact me",
  },
  {
    id: uuid(),
    type: "img",
    left: "50%",
    top: 2680,
    width: 300,
    height: 250,
    inGrid: true,
    isMulti: false,
    center: true,
    src: "https://i.ibb.co/dg8wwp3/Pngtree-contact-us-flat-design-style-5874427.png",
    styleDefault: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "none",
      borderColor: "initial",
      fontWeight: "",
      textAlign: "",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "input",
    left: 50,
    top: 2680,
    width: 250,
    height: 230,
    inGrid: true,
    isMulti: false,
    valueItem: "[Your detail, address]",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(0, 0, 0)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "14px",
      borderRadius: "24px",
      fontFamily: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "[Your detail, address]",
  },
  {
    id: uuid(),
    type: "button",
    left: 679,
    top: 2724,
    width: 167,
    height: 119,
    inGrid: true,
    isMulti: false,
    valueItem: "<Your social networks>",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(0, 0, 0)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "14px",
      borderRadius: "360px",
      fontFamily: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "47px",
      borderSize: "1px",
      id: uuid(),
    },
    src: "",
  },
  {
    type: "icon",
    height: 42,
    width: 76,
    left: 828,
    top: 2706,
    inGrid: true,
    isMulti: false,
    InfoIcon: "Facebook",
    styleDefault: {
      color: "blue",
      backgroundColor: "transparent",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      border: "3px outset #DC143C",
      fontSize: "",
      fontFamily: "",
      borderStyle: "outset",
      borderColor: "rgba(0,0,0,0)",
      fontWeight: "",
      textAlign: "",
      borderWidth: "3px",
      textTransform: "",
      lineHeight: "",
      borderSize: "3px",
    },
    id: uuid(),
    valueItem: "",
    href: "http://localhost:3000/template3",
    textValue: "",
  },
  {
    type: "icon",
    height: 44,
    width: 76,
    left: 615,
    top: 2702,
    inGrid: true,
    isMulti: false,
    InfoIcon: "Instagram",
    styleDefault: {
      color: "rgb(255, 51, 153)",
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      border: "3px outset #DC143C",
      backgroundColor: "rgba(0,0,0,0)",
      fontSize: "",
      fontFamily: "",
      borderStyle: "outset",
      borderColor: "rgba(0,0,0,0)",
      fontWeight: "",
      textAlign: "",
      borderWidth: "3px",
      lineHeight: "",
      borderSize: "3px",
    },
    id: uuid(),
    valueItem: "",
    href: "http://localhost:3000/template3",
    textValue: "",
  },
  {
    type: "icon",
    height: 50,
    width: 87,
    left: 710,
    top: 2843,
    inGrid: true,
    isMulti: false,
    InfoIcon: "Github",
    styleDefault: {
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "50px",
      border: "3px outset #DC143C",
      backgroundColor: "",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "outset",
      borderColor: "rgba(0,0,0,0)",
      fontWeight: "",
      textAlign: "",
      borderWidth: "3px",
      textTransform: "",
      lineHeight: "",
      borderSize: "3px",
    },
    id: uuid(),
    valueItem: "",
    href: "http://localhost:3000/template3",
    textValue: "",
  },
];
