import uuid from "react-uuid";

export const DefaultItemInGridTemplate1 = [
  {
    id: uuid(),
    type: "div",
    left: 0,
    top: 0,
    width: "100%",
    height: 500,
    href: "",
    src: "",
    inGrid: true,
    isMulti: false,
    styleDefault: {
      backgroundColor: "rgb(102, 153, 153)",
      borderColor: "",
      borderRadius: "",
      borderStyle: "",
      borderWidth: "",
      color: "",
      fontFamily: "",
      fontSize: "",
      fontWeight: "",
      lineHeight: "",
      textAlign: "",
      textTransform: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "input",
    left: "50%",
    top: 100,
    width: 500,
    height: 80,
    href: "",
    src: "",
    inGrid: true,
    isMulti: false,
    valueItem: "[Header]",
    center: true,
    styleDefault: {
      backgroundColor: "transparent",
      borderColor: "rgb(204, 204, 204)",
      borderRadius: "",
      borderStyle: "solid",
      borderWidth: "1px",
      color: "rgb(255, 255, 255)",
      fontFamily: "Poppins",
      fontSize: "18px",
      fontWeight: "",
      lineHeight: "26px",
      textAlign: "center",
      textTransform: "",
      border: "1px solid #ccc",
    },
    textValue: "[Header]",
  },
];
