import uuid from "react-uuid";

const leftDefaultText = 50;
const leftDefaultTitle = 100;

export const DefaultItemInGridTemplate4 = [
  {
    id: uuid(),
    type: "div",
    left: 0,
    top: 0,
    width: 1442,
    height: 500,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      backgroundColor: "rgb(1, 34, 65)",
      border: "none",
      borderColor: "rgb(205, 228, 207)",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "none",
      fontWeight: "",
      textAlign: "",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "input",
    left: 328,
    top: 120,
    width: 300,
    height: 52,
    inGrid: true,
    isMulti: false,
    valueItem: "[Enter name]",
    styleDefault: {
      backgroundColor: "transparent",
      fontSize: "24px",
      fontWeight: "bold",
      textAlign: "center",
      border: "none",
      color: "rgb(255, 255, 255)",
      fontFamily: "Poppins",
      lineHeight: "50px",
      textTransform: "uppercase",
      borderRadius: "",
      borderStyle: "groove",
      borderColor: "rgba(0, 0, 0, 0)",
      borderWidth: "1px",
      borderSize: "1px",
    },
    textValue: "[Enter name]",
  },
  {
    id: uuid(),
    type: "input",
    left: 290,
    top: 197,
    width: 400,
    height: 100,
    inGrid: true,
    isMulti: false,
    valueItem: "<Your about>",
    styleDefault: {
      backgroundColor: "transparent",
      fontSize: "18px",
      textAlign: "center",
      border: "none",
      color: "rgb(201, 44, 44)",
      fontFamily: "Poppins",
      lineHeight: "26px",
      borderRadius: "",
      borderStyle: "none",
      borderColor: "initial",
      fontWeight: "",
      borderWidth: "initial",
      textTransform: "",
      borderSize: "initial",
    },
    textValue: "<Your about>",
  },
  {
    id: uuid(),
    type: "img",
    left: 808,
    top: 116,
    width: 300,
    height: 300,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      backgroundColor: "transparent",
      borderColor: "initial",
      borderRadius: "24px",
      border: "none",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "none",
      fontWeight: "",
      textAlign: "",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "div",
    left: -7,
    top: 496,
    width: "100%",
    height: 504,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      backgroundColor: "rgb(255, 210, 48)",
      border: "none",
      borderColor: "rgb(205, 228, 207)",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "none",
      fontWeight: "",
      textAlign: "",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "button",
    left: 701,
    top: 564,
    width: 200,
    height: 48,
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "Education",
    styleDefault: {
      fontWeight: "bold",
      fontSize: "24px",
      color: "rgb(255, 255, 255)",
      border: "none",
      wordSpacing: "4px",
      backgroundColor: "transparent",
      textAlign: "center",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "none",
      borderColor: "initial",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
      borderSize: "initial",
    },
    src: "",
  },
  {
    id: uuid(),
    type: "input",
    left: 689,
    top: 648,
    width: 500,
    height: 100,
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "<Describe>",
    styleDefault: {
      fontWeight: "bold",
      color: "blue",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "<Describe>",
  },
  {
    id: uuid(),
    type: "div",
    left: 0,
    top: 998,
    width: "100%",
    height: 504,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      backgroundColor: "rgb(1, 34, 65)",
      border: "none",
      borderColor: "rgb(205, 228, 207)",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "none",
      fontWeight: "",
      textAlign: "",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "button",
    left: 622,
    top: 1092,
    width: 200,
    height: 48,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "Skills",
    styleDefault: {
      fontWeight: "bold",
      fontSize: "24px",
      color: "var(--primary)",
      border: "none",
      wordSpacing: "4px",
      backgroundColor: "transparent",
      textAlign: "center",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "none",
      borderColor: "initial",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
    },
  },
  {
    id: uuid(),
    type: "input",
    left: 553,
    top: 1204,
    width: 350,
    height: 100,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<List skills>",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(255, 255, 255)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "<List skills>",
  },
  {
    id: uuid(),
    type: "div",
    left: 0,
    top: 1500,
    width: "100%",
    height: 504,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      backgroundColor: "rgb(255, 210, 48)",
      border: "none",
      borderColor: "rgb(205, 228, 207)",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "none",
      fontWeight: "",
      textAlign: "",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "button",
    left: 429,
    top: 1601,
    width: 300,
    height: 48,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "Your projects",
    styleDefault: {
      fontWeight: "bold",
      fontSize: "24px",
      color: "rgb(255, 255, 255)",
      border: "none",
      wordSpacing: "4px",
      backgroundColor: "transparent",
      textAlign: "center",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "none",
      borderColor: "initial",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
    },
  },
  {
    id: uuid(),
    type: "input",
    left: 393,
    top: 1695,
    width: 350,
    height: 100,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Project theme>",
    styleDefault: {
      fontWeight: "bold",
      color: "blue",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "<Project theme>",
  },
  {
    id: uuid(),
    type: "img",
    left: 846,
    top: 1599,
    width: 247,
    height: 211,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      borderColor: "rgb(205, 228, 207)",
      borderRadius: "24px",
      backgroundColor: "transparent",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "",
      fontWeight: "",
      textAlign: "",
      borderWidth: "",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "div",
    left: 0,
    top: 2000,
    width: 1442,
    height: 510,
    inGrid: true,
    isMulti: false,
    valueItem: "",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(255, 255, 255)",
      backgroundColor: "rgb(1, 34, 65)",
      border: "none",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "none",
      borderColor: "initial",
      textAlign: "",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
      borderSize: "initial",
    },
  },
  {
    id: uuid(),
    type: "img",
    left: 545,
    top: 2094,
    width: 285,
    height: 266,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "none",
      borderColor: "initial",
      fontWeight: "",
      textAlign: "",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "img",
    left: 243,
    top: 2227,
    width: 234,
    height: 141,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "none",
      borderColor: "initial",
      fontWeight: "",
      textAlign: "",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
      borderSize: "initial",
    },
    valueItem: "",
    src: "",
  },
  {
    id: uuid(),
    type: "img",
    left: 241,
    top: 2083,
    width: 241,
    height: 134,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "none",
      borderColor: "initial",
      fontWeight: "",
      textAlign: "",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "input",
    left: 902,
    top: 2108,
    width: 238,
    height: 61,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "About work",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(212, 140, 140)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "44px",
      borderSize: "1px",
    },
    textValue: "About work",
  },
  {
    id: uuid(),
    type: "input",
    left: 899,
    top: 2209,
    width: 242,
    height: 128,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Describes>",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(212, 140, 140)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "12px",
      fontFamily: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      lineHeight: "43px",
      borderSize: "1px",
    },
    textValue: "<Describes>",
  },
  {
    id: uuid(),
    type: "div",
    left: 0,
    top: 2498,
    width: 1442,
    height: 508,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      fontWeight: "bold",
      backgroundColor: "rgb(255, 210, 48)",
      textAlign: "center",
      border: "none",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "none",
      borderColor: "initial",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
      borderSize: "initial",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "input",
    left: 287,
    top: 2581,
    width: 250,
    height: 50,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "Contact me",
    styleDefault: {
      fontWeight: "bold",
      color: "var(--primary)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "Contact me",
  },
  {
    id: uuid(),
    type: "img",
    left: 580,
    top: 2539,
    width: 245,
    height: 274,
    inGrid: true,
    isMulti: false,
    src: "https://i.ibb.co/rHpQj5S/Pngtree-contact-our-front-desk-5412876-1.png",
    styleDefault: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "double",
      borderColor: "rgb(253, 216, 216)",
      fontWeight: "",
      textAlign: "",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
      borderSize: "initial",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "input",
    left: 908,
    top: 2588,
    width: 209,
    height: 255,
    inGrid: true,
    isMulti: false,
    valueItem: "[Your detail, address]",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(0, 0, 0)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "14px",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "[Your detail, address]",
  },
  {
    id: uuid(),
    type: "button",
    left: 602,
    top: 2838,
    width: 200,
    height: 30,
    inGrid: true,
    isMulti: false,
    valueItem: "Connect with me",
    styleDefault: {
      color: "blue",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "14px",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      fontWeight: "",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
  },
  {
    id: uuid(),
    type: "input",
    left: 281,
    top: 2648,
    width: 250,
    height: 200,
    inGrid: true,
    isMulti: false,
    valueItem: "Details",
    styleDefault: {
      color: "blue",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "14px",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      fontWeight: "",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "Details",
  },
  {
    type: "icon",
    left: 741,
    top: 2908,
    width: 50,
    height: 52,
    inGrid: true,
    isMulti: false,
    InfoIcon: "Facebook",
    styleDefault: {
      borderWidth: "",
      borderStyle: "",
      borderColor: "",
      padding: "12px",
      backgroundColor: "",
      color: "rgb(33, 55, 228)",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "",
      textAlign: "",
      textTransform: "",
      lineHeight: "",
      borderSize: "",
    },
    href: "http://localhost:3000/template4",
    valueItem: "",
    id: uuid(),
  },
  {
    type: "icon",
    left: 601,
    top: 2906,
    width: 51,
    height: 52,
    inGrid: true,
    isMulti: false,
    InfoIcon: "Instagram",
    styleDefault: {
      borderWidth: "",
      borderStyle: "",
      borderColor: "",
      padding: "12px",
      backgroundColor: "rgba(0, 0, 0, 0)",
      color: "rgb(255, 0, 0)",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "",
      textAlign: "",
      textTransform: "",
      lineHeight: "",
      borderSize: "",
    },
    href: "http://localhost:3000/template4",
    valueItem: "",
    id: uuid(),
  },
];
