import uuid from "react-uuid";

const leftDefaultText = 50;
const leftDefaultTitle = 100;

export const DefaultItemInGridTemplate4 = [
  {
    id: uuid(),
    type: "div",
    left: 0,
    top: 0,
    width: "100%",
    height: 500,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      backgroundColor: "rgb(1, 34, 65)",
      border: "none",
      borderColor: "rgb(205, 228, 207)",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "none",
      fontWeight: "",
      textAlign: "",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "input",
    left: 109,
    top: 80,
    width: 300,
    height: 52,
    inGrid: true,
    isMulti: false,
    valueItem: "[Enter name]",
    styleDefault: {
      backgroundColor: "transparent",
      fontSize: "24px",
      fontWeight: "bold",
      textAlign: "center",
      border: "none",
      color: "rgb(255, 255, 255)",
      fontFamily: "Poppins",
      lineHeight: "50px",
      textTransform: "uppercase",
      borderRadius: "",
      borderStyle: "groove",
      borderColor: "rgba(0, 0, 0, 0)",
      borderWidth: "1px",
      borderSize: "1px",
    },
  },
  {
    id: uuid(),
    type: "input",
    left: 61,
    top: 158,
    width: 400,
    height: 100,
    inGrid: true,
    isMulti: false,
    valueItem: "<Your about>",
    styleDefault: {
      backgroundColor: "transparent",
      fontSize: "18px",
      textAlign: "center",
      border: "none",
      color: "rgb(201, 44, 44)",
      fontFamily: "Poppins",
      lineHeight: "26px",
      borderRadius: "",
      borderStyle: "none",
      borderColor: "initial",
      fontWeight: "",
      borderWidth: "initial",
      textTransform: "",
      borderSize: "initial",
    },
    textValue: "<Your about>",
  },
  {
    id: uuid(),
    type: "img",
    left: "calc(60% + -2px)",
    top: 83,
    width: 300,
    height: 300,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      backgroundColor: "transparent",
      borderColor: "initial",
      borderRadius: "24px",
      border: "none",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "none",
      fontWeight: "",
      textAlign: "",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "div",
    left: 0,
    top: 498,
    width: "100%",
    height: 504,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      backgroundColor: "rgb(255, 210, 48)",
      border: "none",
      borderColor: "rgb(205, 228, 207)",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "none",
      fontWeight: "",
      textAlign: "",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "button",
    left: "50%",
    top: 550,
    width: 200,
    height: 48,
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "Education",
    styleDefault: {
      fontWeight: "bold",
      fontSize: "24px",
      color: "rgb(255, 255, 255)",
      border: "none",
      wordSpacing: "4px",
      backgroundColor: "transparent",
      textAlign: "center",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "none",
      borderColor: "initial",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
    },
  },
  {
    id: uuid(),
    type: "input",
    left: "50%",
    top: 650,
    width: 500,
    height: 100,
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "<Describe>",
    styleDefault: {
      fontWeight: "bold",
      color: "blue",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "<Describe>",
  },
  {
    id: uuid(),
    type: "div",
    left: 0,
    top: 998,
    width: "100%",
    height: 504,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      backgroundColor: "rgb(1, 34, 65)",
      border: "none",
      borderColor: "rgb(205, 228, 207)",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "none",
      fontWeight: "",
      textAlign: "",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "button",
    left: 432,
    top: 1042,
    width: 200,
    height: 48,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "Skills",
    styleDefault: {
      fontWeight: "bold",
      fontSize: "24px",
      color: "var(--primary)",
      border: "none",
      wordSpacing: "4px",
      backgroundColor: "transparent",
      textAlign: "center",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "none",
      borderColor: "initial",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
    },
  },
  {
    id: uuid(),
    type: "input",
    left: 360,
    top: 1128,
    width: 350,
    height: 100,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<List skills>",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(255, 255, 255)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "<List skills>",
  },
  {
    id: uuid(),
    type: "div",
    left: 0,
    top: 1500,
    width: "100%",
    height: 504,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      backgroundColor: "rgb(255, 210, 48)",
      border: "none",
      borderColor: "rgb(205, 228, 207)",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "none",
      fontWeight: "",
      textAlign: "",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "button",
    left: 334,
    top: 1539,
    width: 300,
    height: 48,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "Your projects",
    styleDefault: {
      fontWeight: "bold",
      fontSize: "24px",
      color: "rgb(255, 255, 255)",
      border: "none",
      wordSpacing: "4px",
      backgroundColor: "transparent",
      textAlign: "center",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "none",
      borderColor: "initial",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
    },
  },
  {
    id: uuid(),
    type: "input",
    left: 128,
    top: 1662,
    width: 350,
    height: 100,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Project theme>",
    styleDefault: {
      fontWeight: "bold",
      color: "blue",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "<Project theme>",
  },
  {
    id: uuid(),
    type: "img",
    left: 600,
    top: 1632,
    width: 247,
    height: 211,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      borderColor: "rgb(205, 228, 207)",
      borderRadius: "24px",
      backgroundColor: "transparent",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "",
      fontWeight: "",
      textAlign: "",
      borderWidth: "",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "div",
    left: 0,
    top: 2000,
    width: "100%",
    height: 510,
    inGrid: true,
    isMulti: false,
    valueItem: "",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(255, 255, 255)",
      backgroundColor: "rgb(1, 34, 65)",
      border: "none",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "none",
      borderColor: "initial",
      textAlign: "",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
    },
  },
  {
    id: uuid(),
    type: "img",
    left: 540,
    top: 2180,
    width: 259,
    height: 139,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "none",
      borderColor: "initial",
      fontWeight: "",
      textAlign: "",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "img",
    left: 219,
    top: 2051,
    width: 278,
    height: 150,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "none",
      borderColor: "initial",
      fontWeight: "",
      textAlign: "",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "img",
    left: 224,
    top: 2321,
    width: 282,
    height: 143,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "none",
      borderColor: "initial",
      fontWeight: "",
      textAlign: "",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "input",
    left: 538,
    top: 2060,
    width: 238,
    height: 51,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "Experiences",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(255, 0, 0)",
      backgroundColor: "rgba(0, 0, 0, 0)",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      textTransform: "uppercase",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      lineHeight: "42px",
      borderSize: "1px",
    },
    textValue: "Experiences",
  },
  {
    id: uuid(),
    type: "input",
    left: 225,
    top: 2218,
    width: 258,
    height: 52,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "About work",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(212, 140, 140)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "44px",
      borderSize: "1px",
    },
    textValue: "About work",
  },
  {
    id: uuid(),
    type: "input",
    left: 554,
    top: 2338,
    width: 242,
    height: 118,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Describes>",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(212, 140, 140)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      textTransform: "uppercase",
      boxShadow: "10px 10px 106px -33px rgba(240,43,53,1)",
      borderRadius: "12px",
      fontFamily: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      lineHeight: "43px",
      borderSize: "1px",
    },
    textValue: "<Describes>",
  },
  {
    id: uuid(),
    type: "div",
    left: 0,
    top: 2500,
    width: "100%",
    height: 504,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      fontWeight: "bold",
      backgroundColor: "rgb(255, 210, 48)",
      textAlign: "center",
      border: "none",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "none",
      borderColor: "initial",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
      borderSize: "initial",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "input",
    left: 50,
    top: 2540,
    width: 250,
    height: 50,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "Contact me",
    styleDefault: {
      fontWeight: "bold",
      color: "var(--primary)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "Contact me",
  },
  {
    id: uuid(),
    type: "img",
    left: "calc(calc(calc(60% + 58px) + 19px) + 12px)",
    top: 2533,
    width: 245,
    height: 274,
    inGrid: true,
    isMulti: false,
    src: "https://i.ibb.co/rHpQj5S/Pngtree-contact-our-front-desk-5412876-1.png",
    styleDefault: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "double",
      borderColor: "rgb(253, 216, 216)",
      fontWeight: "",
      textAlign: "",
      borderWidth: "initial",
      textTransform: "",
      lineHeight: "",
      borderSize: "initial",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "input",
    left: 382,
    top: 2537,
    width: 214,
    height: 271,
    inGrid: true,
    isMulti: false,
    valueItem: "[Your detail, address]",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(0, 0, 0)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "14px",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "[Your detail, address]",
  },
  {
    id: uuid(),
    type: "button",
    left: 392,
    top: 2829,
    width: 200,
    height: 30,
    inGrid: true,
    isMulti: false,
    valueItem: "Connect with me",
    styleDefault: {
      color: "blue",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "14px",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      fontWeight: "",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
  },
  {
    id: uuid(),
    type: "input",
    left: 50,
    top: 2610,
    width: 250,
    height: 200,
    inGrid: true,
    isMulti: false,
    valueItem: "Details",
    styleDefault: {
      color: "blue",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "14px",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      fontWeight: "",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "Details",
  },
  {
    type: "icon",
    left: 397,
    top: 2897,
    width: 60,
    height: 60,
    inGrid: true,
    isMulti: false,
    InfoIcon: "Facebook",
    styleDefault: {
      borderWidth: "1px",
      borderStyle: "solid",
      borderColor: "rgb(255, 204, 255)",
      padding: "12px",
      backgroundColor: "",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "",
      textAlign: "",
      textTransform: "",
      lineHeight: "",
    },
    src: "",
    href: "http://localhost:3000/template4",
    valueItem: "",
    id: uuid(),
  },
  {
    type: "icon",
    left: 529,
    top: 2894,
    width: 60,
    height: 60,
    inGrid: true,
    isMulti: false,
    InfoIcon: "Instagram",
    styleDefault: {
      borderWidth: "1px",
      borderStyle: "solid",
      borderColor: "rgb(255, 204, 255)",
      padding: "12px",
      backgroundColor: "",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "",
      textAlign: "",
      textTransform: "",
      lineHeight: "",
    },
    src: "",
    href: "http://localhost:3000/template4",
    valueItem: "",
    id: uuid(),
  },
];
