import uuid from "react-uuid";

export const DefaultItemInGridTemplate5 = [
  {
    id: uuid(),
    type: "img",
    left: "0%",
    top: 0,
    width: "100%",
    height: 502,
    inGrid: true,
    isMulti: false,
    src: "https://images.unsplash.com/photo-1497864149936-d3163f0c0f4b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80",
    styleDefault: {
      backgroundColor: "",
      padding: 0,
      borderWidth: "0px",
      borderStyle: "none",
      borderColor: "transparent",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "",
      textAlign: "",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "div",
    left: "0%",
    top: 500,
    width: "100%",
    height: 510,
    inGrid: true,
    isMulti: false,
    valueItem: "",
    styleDefault: {
      backgroundColor: "rgb(24, 45, 71)",
      borderWidth: "0px",
      borderStyle: "none",
      borderColor: "transparent",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "",
      textAlign: "",
      textTransform: "",
      lineHeight: "",
    },
  },
  {
    id: uuid(),
    type: "div",
    left: "0%",
    top: 953,
    width: 1442,
    height: 541,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      backgroundColor: "rgb(9, 29, 53)",
      border: "none",
      borderWidth: "0px",
      borderStyle: "none",
      borderColor: "transparent",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "",
      textAlign: "",
      textTransform: "",
      lineHeight: "",
      borderSize: "0px",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "div",
    left: "-1.1506276150627615%",
    top: 1485,
    width: 1471,
    height: 534,
    inGrid: true,
    isMulti: false,
    valueItem: "",
    styleDefault: {
      backgroundColor: "rgb(24, 45, 71)",
      borderWidth: "0px",
      borderStyle: "none",
      borderColor: "transparent",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "",
      textAlign: "",
      textTransform: "",
      lineHeight: "",
      borderSize: "0px",
    },
  },
  {
    id: uuid(),
    type: "div",
    left: "0%",
    top: 2000,
    width: 1442,
    height: 510,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      backgroundColor: "rgb(9, 29, 53)",
      borderWidth: "0px",
      borderStyle: "none",
      borderColor: "transparent",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "",
      textAlign: "",
      textTransform: "",
      lineHeight: "",
      borderSize: "0px",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "div",
    left: "0",
    top: 2499,
    width: "100%",
    height: 510,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      backgroundColor: "rgb(24, 45, 71)",
      borderWidth: "0px",
      borderStyle: "none",
      borderColor: "transparent",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "",
      textAlign: "",
      textTransform: "",
      lineHeight: "",
      borderSize: "0px",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "img",
    left: "56.0991533144923%",
    top: 134,
    width: 300,
    height: 350,
    inGrid: true,
    isMulti: false,
    src: "https://i.imgur.com/uo3V1fn.png",
    styleDefault: {
      borderRadius: "50px",
      backgroundColor: "transparent",
      borderColor: "transparent",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "",
      fontWeight: "",
      textAlign: "",
      borderWidth: "",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "input",
    left: "21.63124786007346%",
    top: 181,
    width: 229,
    height: 47,
    inGrid: true,
    isMulti: false,
    valueItem: "[Enter title]",
    styleDefault: {
      backgroundColor: "transparent",
      fontSize: "24px",
      fontWeight: "bold",
      textAlign: "center",
      border: "1px solid #ccc",
      color: "rgb(220, 20, 60)",
      fontFamily: "Poppins",
      lineHeight: "26px",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
    },
    textValue: "[Enter title]",
  },
  {
    id: uuid(),
    type: "input",
    left: "13.424956040831242%",
    top: 284,
    width: 364,
    height: 49,
    inGrid: true,
    isMulti: false,
    valueItem: "<Enter text>",
    styleDefault: {
      backgroundColor: "transparent",
      fontSize: "18px",
      textAlign: "center",
      border: "1px solid #ccc",
      color: "rgb(255, 255, 224)",
      fontFamily: "Poppins",
      lineHeight: "26px",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      fontWeight: "",
      borderWidth: "1px",
      textTransform: "",
    },
    textValue: "<Enter text>",
  },
  {
    id: uuid(),
    type: "button",
    left: "9.500693481276006%",
    top: 25,
    width: 200,
    height: 48,
    inGrid: true,
    isMulti: false,
    valueItem: "Enter text !!!",
    styleDefault: {
      backgroundColor: "transparent",
      fontSize: "18px",
      textAlign: "center",
      border: "none",
      color: "rgb(255, 0, 0)",
      fontFamily: "Poppins",
      lineHeight: "26px",
      borderBottom: "1px double #ccc ",
      borderRight: "1px double #ccc ",
      padding: 12,
      minHeight: 48,
      borderRadius: "",
      borderStyle: "none double double none",
      borderColor: "",
      fontWeight: "",
      borderWidth: "",
      textTransform: "",
    },
  },
  {
    id: uuid(),
    type: "img",
    left: "14.694113823780306%",
    top: 560,
    width: 296,
    height: 310,
    inGrid: true,
    isMulti: false,
    src: "https://i.imgur.com/MCXD87T.png",
    styleDefault: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
      borderRight: "1px double #ccc",
      borderTop: "1px double #ccc",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "double double none none",
      borderColor: "",
      fontWeight: "",
      textAlign: "",
      borderWidth: "",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "button",
    left: "57.69764216366158%",
    top: 575,
    width: 200,
    height: 48,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "About",
    styleDefault: {
      fontWeight: "bold",
      fontSize: "24px",
      color: "rgb(106, 90, 205)",
      border: "1px solid #ccc",
      wordSpacing: "4px",
      backgroundColor: "transparent",
      textTransform: "uppercase",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      textAlign: "center",
      borderWidth: "1px",
      lineHeight: "",
      borderSize: "1px",
    },
    src: "",
  },
  {
    id: uuid(),
    type: "input",
    left: "56.033287101248256%",
    top: 653,
    width: 301,
    height: 67,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Your About>",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(255, 255, 255)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
      borderSize: "1px",
    },
    textValue: "<Your About>",
  },
  {
    id: uuid(),
    type: "input",
    left: "50.41608876560334%",
    top: 1022,
    width: 400,
    height: 50,
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "[Your Offered Services]",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(106, 90, 205)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
      borderSize: "1px",
    },
    textValue: "[Your Offered Services]",
  },
  {
    id: uuid(),
    type: "input",
    left: "50.55478502080444%",
    top: 1118,
    width: 561,
    height: 51,
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "<Describe>",
    styleDefault: {
      color: "rgb(255, 255, 255)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      margin: "0 auto",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      fontWeight: "",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "<Describe>",
  },
  {
    id: uuid(),
    type: "input",
    left: "23.214213174403287%",
    top: 1649,
    width: 243,
    height: 53,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "[Feedback from client]",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(201, 171, 122)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "[Feedback from client]",
  },
  {
    id: uuid(),
    type: "input",
    left: "18.979334838294097%",
    top: 1737,
    width: 349,
    height: 50,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Your slogan>",
    styleDefault: {
      color: "rgb(255, 255, 255)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      margin: "0 auto",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      fontWeight: "",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "<Your slogan>",
  },
  {
    id: uuid(),
    type: "input",
    left: "49.65325936199723%",
    top: 2071,
    width: 400,
    height: 50,
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "[Your project]",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(179, 7, 60)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
      borderSize: "1px",
    },
    textValue: "[Your project]",
  },
  {
    id: uuid(),
    type: "input",
    left: "51.61125586847649%",
    top: 2179,
    width: 600,
    height: 48,
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "<Technology used>",
    styleDefault: {
      color: "rgb(255, 255, 255)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      margin: "0 auto",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      fontWeight: "",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "<Technology used>",
  },
  {
    id: uuid(),
    type: "input",
    left: "50.069348127600556%",
    top: 2549,
    width: 250,
    height: 100,
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "Looking ForWard to working with everyone!",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(255, 248, 220)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      lineHeight: "32px",
      textTransform: "uppercase",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      borderSize: "1px",
    },
    textValue: "Looking ForWard to working with everyone!",
  },
  {
    id: uuid(),
    type: "img",
    left: "50.13869625520111%",
    top: 2688,
    width: 183,
    height: 180,
    inGrid: true,
    isMulti: false,
    center: true,
    src: "https://i.imgur.com/PAvCNbh.png",
    styleDefault: {
      borderRadius: "50px",
      backgroundColor: "transparent",
      borderColor: "transparent",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "",
      fontWeight: "",
      textAlign: "",
      borderWidth: "",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "button",
    left: "18.249438541310017%",
    top: 2694,
    width: 150,
    height: 50,
    inGrid: true,
    isMulti: false,
    valueItem: "About",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(255, 255, 255)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "14px",
      textTransform: "uppercase",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      lineHeight: "",
      borderSize: "1px",
    },
    src: "",
  },
  {
    id: uuid(),
    type: "input",
    left: "63.24549237170598%",
    top: 2680,
    width: 220,
    height: 93,
    inGrid: true,
    isMulti: false,
    valueItem: "[Address detail,your number]",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(255, 255, 255)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "14px",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "50px",
      borderSize: "1px",
    },
    textValue: "[Address detail,your number]",
  },
  {
    id: uuid(),
    type: "a",
    left: "63.730929264909854%",
    top: 2812,
    width: 100,
    height: 50,
    inGrid: true,
    isMulti: false,
    href: "http://localhost:3000/template2#",
    textValue: "facebook",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(255, 255, 255)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      minHeight: 50,
      fontSize: "14px",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      textAlign: "center",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
      borderSize: "1px",
    },
    valueItem: "facebook",
  },
  {
    id: uuid(),
    type: "a",
    left: "75.8160736773078%",
    top: 2810,
    width: 100,
    height: 50,
    inGrid: true,
    isMulti: false,
    href: "http://localhost:3000/template2#",
    textValue: "Youtube",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(255, 255, 255)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      minHeight: 50,
      fontSize: "14px",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      textAlign: "center",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
      borderSize: "1px",
    },
    valueItem: "Youtube",
  },
  {
    type: "img",
    left: "56.10263522884882%",
    top: 1604,
    id: uuid(),
    width: 261,
    height: 257,
    inGrid: true,
    isMulti: false,
    InfoIcon: "",
    styleDefault: {
      backgroundColor: "",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "",
      borderColor: "",
      fontWeight: "",
      textAlign: "",
      borderWidth: "",
      textTransform: "",
      lineHeight: "",
    },
    src: "",
    href: "",
    valueItem: "",
  },
  {
    type: "input",
    left: "16.620337861756393%",
    top: 2795,
    id: uuid(),
    width: 200,
    height: 60,
    inGrid: true,
    isMulti: false,
    InfoIcon: "",
    styleDefault: {
      backgroundColor: "transparent",
      color: "rgb(204, 204, 204)",
      borderWidth: "1px",
      borderStyle: "outset",
      borderColor: "rgb(117, 117, 117)",
      padding: "12px",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "",
      textAlign: "",
      textTransform: "",
      lineHeight: "",
      borderSize: "1px",
    },
    valueItem: "[Your detail, address]",
    textValue: "[Your detail, address]",
  },
];
