import uuid from "react-uuid";

export const DefaultItemInGridTemplate2 = [
  {
    id: uuid(),
    type: "img",
    left: 0,
    top: 0,
    width: "100%",
    height: 502,
    inGrid: true,
    isMulti: false,
    src: "https://images.unsplash.com/photo-1497864149936-d3163f0c0f4b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80",
    styleDefault: {
      backgroundColor: "",
      padding: 0,
      borderWidth: "0px",
      borderStyle: "none",
      borderColor: "transparent",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "",
      textAlign: "",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "div",
    left: 0,
    top: 500,
    width: "100%",
    height: 510,
    inGrid: true,
    isMulti: false,
    valueItem: "",
    styleDefault: {
      backgroundColor: "rgb(24, 45, 71)",
      borderWidth: "0px",
      borderStyle: "none",
      borderColor: "transparent",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "",
      textAlign: "",
      textTransform: "",
      lineHeight: "",
    },
  },
  {
    id: uuid(),
    type: "div",
    left: 0,
    top: 1000,
    width: "100%",
    height: 510,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      backgroundColor: "rgb(9, 29, 53)",
      border: "none",
      borderWidth: "0px",
      borderStyle: "none",
      borderColor: "transparent",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "",
      textAlign: "",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "div",
    left: 0,
    top: 1500,
    width: "100%",
    height: 510,
    inGrid: true,
    isMulti: false,
    valueItem: "",
    styleDefault: {
      backgroundColor: "rgb(24, 45, 71)",
      borderWidth: "0px",
      borderStyle: "none",
      borderColor: "transparent",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "",
      textAlign: "",
      textTransform: "",
      lineHeight: "",
    },
  },
  {
    id: uuid(),
    type: "div",
    left: 0,
    top: 2000,
    width: "100%",
    height: 510,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      backgroundColor: "rgb(9, 29, 53)",
      borderWidth: "0px",
      borderStyle: "none",
      borderColor: "transparent",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "",
      textAlign: "",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "div",
    left: 0,
    top: 2500,
    width: "100%",
    height: 510,
    inGrid: true,
    isMulti: false,
    styleDefault: {
      backgroundColor: "rgb(24, 45, 71)",
      borderWidth: "0px",
      borderStyle: "none",
      borderColor: "transparent",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      fontWeight: "",
      textAlign: "",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "img",
    left: "60%",
    top: 80,
    width: 300,
    height: 350,
    inGrid: true,
    isMulti: false,
    src: "https://i.imgur.com/uo3V1fn.png",
    styleDefault: {
      borderRadius: "50px",
      backgroundColor: "transparent",
      borderColor: "transparent",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "",
      fontWeight: "",
      textAlign: "",
      borderWidth: "",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "input",
    left: 100,
    top: 150,
    width: 400,
    height: 50,
    inGrid: true,
    isMulti: false,
    valueItem: "[Enter title]",
    styleDefault: {
      backgroundColor: "transparent",
      fontSize: "24px",
      fontWeight: "bold",
      textAlign: "center",
      border: "1px solid #ccc",
      color: "rgb(220, 20, 60)",
      fontFamily: "Poppins",
      lineHeight: "26px",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
    },
    textValue: "[Enter title]",
  },
  {
    id: uuid(),
    type: "input",
    left: 50,
    top: 250,
    width: 500,
    height: 48,
    inGrid: true,
    isMulti: false,
    valueItem: "<Enter text>",
    styleDefault: {
      backgroundColor: "transparent",
      fontSize: "18px",
      textAlign: "center",
      border: "1px solid #ccc",
      color: "rgb(255, 255, 224)",
      fontFamily: "Poppins",
      lineHeight: "26px",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      fontWeight: "",
      borderWidth: "1px",
      textTransform: "",
    },
    textValue: "<Enter text>",
  },
  {
    id: uuid(),
    type: "button",
    left: 12,
    top: 12,
    width: 200,
    height: 48,
    inGrid: true,
    isMulti: false,
    valueItem: "",
    styleDefault: {
      backgroundColor: "transparent",
      fontSize: "18px",
      textAlign: "center",
      border: "none",
      color: "rgb(255, 0, 0)",
      fontFamily: "Poppins",
      lineHeight: "26px",
      borderBottom: "1px double #ccc ",
      borderRight: "1px double #ccc ",
      padding: 12,
      minHeight: 48,
      borderRadius: "",
      borderStyle: "none double double none",
      borderColor: "",
      fontWeight: "",
      borderWidth: "",
      textTransform: "",
    },
  },
  {
    id: uuid(),
    type: "img",
    left: "60%",
    top: 560,
    width: 300,
    height: 350,
    inGrid: true,
    isMulti: false,
    src: "https://i.imgur.com/MCXD87T.png",
    styleDefault: {
      borderRadius: "24px",
      backgroundColor: "transparent",
      border: "none",
      borderRight: "1px double #ccc",
      borderTop: "1px double #ccc",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "double double none none",
      borderColor: "",
      fontWeight: "",
      textAlign: "",
      borderWidth: "",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "button",
    left: 100,
    top: 650,
    width: 200,
    height: 48,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "",
    styleDefault: {
      fontWeight: "bold",
      fontSize: "24px",
      color: "rgb(106, 90, 205)",
      border: "1px solid #ccc",
      wordSpacing: "4px",
      backgroundColor: "transparent",
      textTransform: "uppercase",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      textAlign: "",
      borderWidth: "1px",
      lineHeight: "",
    },
  },
  {
    id: uuid(),
    type: "input",
    left: 50,
    top: 740,
    width: 500,
    height: 48,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Your About>",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(255, 255, 255)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "<Your About>",
  },
  {
    id: uuid(),
    type: "input",
    left: "50%",
    top: 1040,
    width: 400,
    height: 48,
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "[Your Offered Services]",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(106, 90, 205)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "[Your Offered Services]",
  },
  {
    id: uuid(),
    type: "input",
    left: "50%",
    top: 1120,
    width: 600,
    height: 48,
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "<Describe>",
    styleDefault: {
      color: "rgb(255, 255, 255)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      margin: "0 auto",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      fontWeight: "",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "<Describe>",
  },
  {
    id: uuid(),
    type: "img",
    left: 50,
    top: 1540,
    width: 400,
    height: 400,
    inGrid: true,
    isMulti: false,
    heading: true,
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(201, 171, 122)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      height: 400,
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "input",
    left: "55%",
    top: 1540,
    width: 300,
    height: 48,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "[Feedback from client]",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(201, 171, 122)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "[Feedback from client]",
  },
  {
    id: uuid(),
    type: "input",
    left: "50%",
    top: 1620,
    width: 400,
    height: 48,
    inGrid: true,
    isMulti: false,
    heading: true,
    valueItem: "<Your slogan>",
    styleDefault: {
      color: "rgb(255, 255, 255)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      margin: "0 auto",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      fontWeight: "",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "<Your slogan>",
  },
  {
    id: uuid(),
    type: "input",
    left: "50%",
    top: 2040,
    width: 400,
    height: 48,
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "[Your project]",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(179, 7, 60)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "[Your project]",
  },
  {
    id: uuid(),
    type: "input",
    left: "50%",
    top: 2120,
    width: 600,
    height: 48,
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "<Technology used>",
    styleDefault: {
      color: "rgb(255, 255, 255)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      margin: "0 auto",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      fontWeight: "",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "<Technology used>",
  },
  {
    id: uuid(),
    type: "input",
    left: "50%",
    top: 2540,
    width: 250,
    height: 100,
    inGrid: true,
    isMulti: false,
    heading: true,
    center: true,
    valueItem: "Looking ForWard to working with everyone!",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(255, 248, 220)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "18px",
      lineHeight: "32px",
      textTransform: "uppercase",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
    },
    textValue: "Looking ForWard to working with everyone!",
  },
  {
    id: uuid(),
    type: "img",
    left: "50%",
    top: 2680,
    width: 200,
    height: 250,
    inGrid: true,
    isMulti: false,
    center: true,
    src: "https://i.imgur.com/PAvCNbh.png",
    styleDefault: {
      borderRadius: "50px",
      backgroundColor: "transparent",
      borderColor: "transparent",
      color: "",
      fontSize: "",
      fontFamily: "",
      borderStyle: "",
      fontWeight: "",
      textAlign: "",
      borderWidth: "",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "",
  },
  {
    id: uuid(),
    type: "input",
    left: 50,
    top: 2780,
    width: 300,
    height: 100,
    inGrid: true,
    isMulti: false,
    valueItem: "[Your detail, address]",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(255, 255, 255)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      height: 100,
      fontSize: "14px",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "[Your detail, address]",
  },
  {
    id: uuid(),
    type: "button",
    left: "70%",
    top: 2600,
    width: 200,
    height: 30,
    inGrid: true,
    isMulti: false,
    valueItem: "",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(255, 255, 255)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "14px",
      textTransform: "uppercase",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      lineHeight: "",
    },
  },
  {
    id: uuid(),
    type: "input",
    left: "64%",
    top: 2680,
    width: 350,
    height: 100,
    inGrid: true,
    isMulti: false,
    valueItem: "[Address detail,your number]",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(255, 255, 255)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      textAlign: "center",
      minHeight: 50,
      fontSize: "14px",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    textValue: "[Address detail,your number]",
  },
  {
    id: uuid(),
    type: "a",
    left: "62%",
    top: 2880,
    width: 100,
    height: 30,
    inGrid: true,
    isMulti: false,
    href: "http://localhost:3000/template2#",
    textValue: "facebook",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(255, 255, 255)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      minHeight: 50,
      fontSize: "14px",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      textAlign: "center",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "facebook",
  },
  {
    id: uuid(),
    type: "a",
    left: "74%",
    top: 2880,
    width: 100,
    height: 30,
    inGrid: true,
    isMulti: false,
    href: "http://localhost:3000/template2#",
    textValue: "Instagram",
    valueItem: "Instagram",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(255, 255, 255)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      minHeight: 50,
      fontSize: "14px",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      textAlign: "center",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
  },
  {
    id: uuid(),
    type: "a",
    left: "86%",
    top: 2880,
    width: 100,
    height: 30,
    inGrid: true,
    isMulti: false,
    href: "http://localhost:3000/template2#",
    textValue: "Youtube",
    styleDefault: {
      fontWeight: "bold",
      color: "rgb(255, 255, 255)",
      backgroundColor: "transparent",
      border: "1px solid #ccc",
      minHeight: 50,
      fontSize: "14px",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      textAlign: "center",
      fontFamily: "",
      borderRadius: "",
      borderStyle: "solid",
      borderColor: "rgb(204, 204, 204)",
      borderWidth: "1px",
      textTransform: "",
      lineHeight: "",
    },
    valueItem: "Youtube",
  },
];
