export const colors = [
  "rgba(0,0,0,0)",
  "#000",
  "#fff",
  "#00FFFF",
  "#FF0000",
  "#757575",
  "#000080",
  "#000033",
];
export const fontFamilys = [
  "Poppins",
  "Monospace",
  "Sf mono",
  "Acme",
  "Alegreya",
  "Alegreya+Sans",
  "Anton",
  "Archivo",
  "Archivo+Black",
  "Archivo+Narrow",
  "Arimo",
  "Arvo",
  "Asap",
  "Asap+Condensed",
  "Bitter",
  "Bowlby+One+SC",
  "Bree+Serif",
  "Cabin",
  "Cairo",
  "Catamaran",
  "Crete+Round",
  "Crimson+Text",
  "Cuprum",
];

export const borderStyles = [
  "hidden",
  "dotted",
  "dashed",
  "solid",
  "groove",
  "outset",
  "double",
];
